### ISSUE TITLE
Duplicate persons in imdbpy2sql database, probably normal/canonical parser problem

### ISSUE THREAD

**Issue by darklow** [alberanid/imdbpy#10]
Just noticed database contains two entries for same person:
```
   id    |        name         | imdb_index | gender | name_pcode_cf | name_pcode_nf | surname_pcode |              md5sum              
---------+---------------------+------------+---------+--------+---------------+---------------+---------------+----------------------------------
 1520700 | Toro, Guillermo del |            |  m      | T6246         | G4653         | T6            | 6fa07d318a205b82ef40a5c76db0974e
 2709933 | del Toro, Guillermo |            |         | D4362         | G4653         | D436          | 99b042e07b27b0321ca6e19f126c67f0
```

Could this be related to some bug in name parsing im imdbpy2sql script?
One name appears in normal way another in canonical.

First name has 100 movies
Second name has 69 movies

All of 169 movies belong to real Guillermo del Toro, which means that this must be one person instead of two.

In few days will update to latest text files and see if there are any changes, but i think bug can be because of middle "... del ..." name

**Comment by alberanid** [comment]
closing the issue in the hope it's no longer happening.
