### ISSUE TITLE
Switch to a calendar versioning scheme

### ISSUE THREAD

**Issue by uyar** [alberanid/imdbpy#112]
A calendar versioning scheme might make more sense for IMDbPY. This way, users might have a better chance of estimating whether their version of IMDbPY will work with the latest markup on IMDb.

http://calver.org/

**Comment by alberanid** [comment]
I'd like to switch to the calendar versioning scheme, for the next release (or the one after that).

Which form is preferred? `imdbpy-YYYY.0M.0D`? `imdbpy-YYYY0M0D`?

Does it make sense to still have the "dev" modifier? We can probably skip it altogether, I guess.

Is it still needed to do "official" releases? I assume we can just release a new version on sourceforge when there enough fixes to justify it.

**Comment by uyar** [comment]
I'm writing on my phone, so I'll keep it short for now. I think we should look into how youtube-dl handles this. Similar project with a long history of calendar versioning.

**Comment by alberanid** [comment]
On master we are switching to a YYYY.0M.0D scheme; I've introduced the imdb.version module.

Only thing I don't like is the fact that, on build, setuptools strips the leading zeroes with this warning:
```
/usr/lib/python3/dist-packages/setuptools/dist.py:473: UserWarning: Normalizing '2020.06.13' to '2020.6.13'
```

It's a known missing feature: https://github.com/pypa/setuptools/issues/308
A fix is on its way: https://github.com/pypa/setuptools/pull/2026

Let's keep master this way for a little; if there are any problems, we'll revert before the next "official" release.

**Comment by alberanid** [comment]
Done.
