### ISSUE TITLE
Are the imdb datasets current? Getting incompatible files

### ISSUE THREAD

**Issue by ElOsoGroso** [alberanid/imdbpy#122]
#### Issue description

The documentation leads me to https://datasets.imdbws.com/, but the imdbpy2sq.py script doesn't reference the files downloaded from there.

#### Version of IMDbPY, Python and OS

Python3

#### Steps to reproduce the issue

The links listed here:
https://datasets.imdbws.com/

Do not correlate with the datasets that imdbpy2sql.py references. They reference files like distributors.list.gz, and these files aren't available to download. 

```
#!python

python imdbpy2sql.py -d C:/Users/Terik/Downloads/directory/ -u mysql:root@password@localhost/imdb

WARNING Complete error:  [Errno 2] No such file or directory: 'C:/Users/Terik/Downloads/directory/distributors.list.gz'
WARNING WARNING WARNING
WARNING unable to read the "C:/Users/Terik/Downloads/directory/miscellaneous-companies.list.gz" file.
WARNING The file will be skipped, and the contained
WARNING information will NOT be stored in the database.
WARNING Complete error:  [Errno 2] No such file or directory: 


#### What's the expected result?

Expected the database to populate with the downloaded datasets.


#### What's the actual result?
Doesn't recognize the downloaded datasets.


#### Additional details

-

**Comment by pgjensen** [comment]
https://github.com/alberanid/imdbpy/issues/60

**Comment by alberanid** [comment]
The old data set - no longer updated - can be found at ftp://ftp.funet.fi/pub/mirrors/ftp.imdb.com/pub/frozendata/ (but it doesn't contain the movie IDs)

I'm working on a parser of the new dataset, but it will take some time. See #60
