### ISSUE TITLE
How to obtain the synopsis of a movie?

### ISSUE THREAD

**Issue by yiqingzhu007** [alberanid/imdbpy#129]
#### Issue description

I have been investigating this for a while... but I still don't know how to obtain the synopsis of a movie. 

#### Version of IMDbPY, Python and OS

- **Python:** python 3.5.1
- **IMDbPY:** 6.3dev20180107

```
#!python
from imdb import IMDb
ia = IMDb()
god_father = ia.get_movie('0068646')
print(god_father.get('plot'))  #this returns the plot summaries
print(god_father.get('synopsis'))  #this returns 'None'
```

#### What's the expected result?

- http://www.imdb.com/title/tt0068646/plotsummary?ref_=tt_ql_stry_2
There is a synopsis available for God Father (1972) on the website but the code returns nothing.

- I also tried populating the old archives (the plot.list.gz from ftp://ftp.funet.fi/pub/mirrors/ftp.imdb.com/pub/frozendata) into SQL using imdbpy2sql.py, but I cannot find synopsis from SQL database either. I'm not sure if there are any synopses included in the plit.list.gz.

Did I target the wrong file? Is there a way to find the synopsis of a movie?

Thanks a lot!

**Comment by alberanid** [comment]
hi @yiqingzhu007 : yes, the parser for synopsis was broken.  Please try again using the version in the repository, since I've just committed a fix.

About the (old) SQL files: yes, the synopsis information are not contained there, so you're forced to use the web parsers.
