### ISSUE TITLE
Support for foreign keys

### ISSUE THREAD

**Issue by andrewdbate** [alberanid/imdbpy#130]
Commit 1d937ce40106dbb9a5567dc9e3c8a4aa10acdc2e removed support for foreign keys.

This was not documented anywhere, and I had to go through the commit history.

Several publications (e.g., database publications) which use `imdbpy` (and `imdbpy2sql` in particular) rely on foreign keys being created.

Please can you bring back support for this, or at least clearly document that support for foreign keys is now missing and direct users to an old version.

**Comment by alberanid** [comment]
Hi @andrewdbate ,
the old schema of the database, with foreign keys, should still be available in the https://github.com/alberanid/imdbpy/tree/imdbpy-legacy branch, which is at the moment (mostly) unsupported.
In master foreign keys were removed because their creation was problematic with some databases.

The main problem here is that the plain text data files that the 'sql' data access system parsed, is no longer supported by IMDb since the end of 2017, so you will not have any new data from them.
So, we have no real reason to update it.

IMDb now release a new set of data (that we call 's3', since they were originally distributed only on AWS S3), with fewer data, but easier to parse.
You can parse them using the version of IMDbPY in master (will be released after we receive some feedback); see https://github.com/alberanid/imdbpy/blob/master/docs/README.s3.txt

Hope this helps.

**Comment by andrewdbate** [comment]
I currently have a MariaDB database using InnoDB tables populated using the last version of the data published in the old format (from about the 22 December 2017 I believe) that was created using version 6.2 of `imdbpy2sql`.

Could I add the foreign key constraints to my existing database by looking at the diff for commit 1d937ce40106dbb9a5567dc9e3c8a4aa10acdc2e, or is it not going to be as easy as that?

Are you aware of any issues with using https://github.com/alberanid/imdbpy/tree/imdbpy-legacy with MariaDB and InnoDB, or should is it expected to work provided the data supplied is in the old format?

Would it be possible to update the documentation at https://github.com/alberanid/imdbpy/tree/imdbpy-legacy to explain that you cannot migrate to the Python 3 version of `imdbpy` if you require foreign keys to be created?

Many thanks!

**Comment by andrewdbate** [comment]
It is also worth noting that `adding foreign keys (this may take a while)` is still printed to the standard out by `imdbpy2sql` in version 6.2. This should probably be removed also.

**Comment by andrewdbate** [comment]
Here is the documentation for how to add foreign keys to the SQL database generated using the IMDbPY version 6.2 script, running on Ubuntu 17.10 with MariaDB 10.1. I hope this might help someone else.

The idea is to add back by manually the foreign key constrants that were removed by 1d937ce40106dbb9a5567dc9e3c8a4aa10acdc2e.

Looking at that commit diff, the foreign key constraints we need to add are:
```sql
ALTER TABLE aka_name ADD FOREIGN KEY (person_id) REFERENCES name(id);

ALTER TABLE aka_title
ADD FOREIGN KEY (kind_id) REFERENCES kind_type(id),
ADD FOREIGN KEY (episode_of_id) REFERENCES aka_title(id);

ALTER TABLE cast_info
ADD FOREIGN KEY (person_id) REFERENCES name(id),
ADD FOREIGN KEY (movie_id) REFERENCES title(id),
ADD FOREIGN KEY (person_role_id) REFERENCES char_name(id),
ADD FOREIGN KEY (role_id) REFERENCES role_type(id);

ALTER TABLE complete_cast
ADD FOREIGN KEY (movie_id) REFERENCES title(id),
ADD FOREIGN KEY (subject_id) REFERENCES comp_cast_type(id),
ADD FOREIGN KEY (status_id) REFERENCES comp_cast_type(id);

ALTER TABLE movie_companies
ADD FOREIGN KEY (movie_id) REFERENCES title(id),
ADD FOREIGN KEY (company_id) REFERENCES company_name(id),
ADD FOREIGN KEY (company_type_id) REFERENCES company_type(id);

ALTER TABLE movie_keyword
ADD FOREIGN KEY (movie_id) REFERENCES title(id),
ADD FOREIGN KEY (keyword_id) REFERENCES keyword(id);

ALTER TABLE movie_info
ADD FOREIGN KEY (movie_id) REFERENCES title(id),
ADD FOREIGN KEY (info_type_id) REFERENCES info_type(id);

ALTER TABLE movie_link
ADD FOREIGN KEY (movie_id) REFERENCES title(id),
ADD FOREIGN KEY (link_type_id) REFERENCES link_type(id);

ALTER TABLE person_info
ADD FOREIGN KEY (person_id) REFERENCES name(id),
ADD FOREIGN KEY (info_type_id) REFERENCES info_type(id);
```
Executing these commands against your database should complete without error.

There are also two more foreign key constraints we need to add, namely:
```sql
ALTER TABLE movie_link ADD FOREIGN KEY (linked_movie_id) REFERENCES title(id);
ALTER TABLE aka_title ADD FOREIGN KEY (movie_id) REFERENCES title(id);
```
However, if you try to execute these against your database, they will fail with an error:
```
Fails with ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails.
```
Next I show the steps taken to debug this against the MariaDB database (in order to determine the root cause), and describe possible fixes.

For the first problematic `ALTER TABLE`, the following query shows us the `linked_movie_id`s that would violate referential integrity should the foreign key be added:
```sql
SELECT DISTINCT linked_movie_id
FROM movie_link
WHERE linked_movie_id NOT IN (SELECT id FROM title)
```
This query returns id `4730462`. There is no movie with this id in the parent table (i.e. the `title` table), so one fix is to delete all records in the `movie_link` table with `linked_movie_id = 4730462`.

Now if we run
```sql
ALTER TABLE movie_link ADD FOREIGN KEY (linked_movie_id) REFERENCES title(id);
```
it completes without error.

We use the same idea to debug the second problematic table, using the following query:
```sql
SELECT movie_id
FROM aka_title
WHERE movie_id NOT IN (SELECT id FROM title)
```
This query result shows that there are records with `movie_id = 0` in the field. A `movie_id` of `0` is bad because there is no record in the `title` table with an `id` of `0`.

The number of broken entries is small, so I just fixed them by hand by looking up what each record is supposed to link to using the IMDb website. You can't just delete all the bad records because some are required due to the foreign keys constraints we added earlier. (If you try deleting them you will get an error.)

Here are the `movie_id`s that I added by hand as individual table updates:
```
id       movie_id
100001   3246517
50004    2270910
50,003   475,419
50001    73710
50002    73710
562491   4674115
50005    4279371
167804   Delete this row (seems to be a movie that was cancelled?)
167805   Delete this row (there is no movie with this AKA name on the website)
```

Finally, I noticed that there were some junk entries in the `aka_title` table. To see these, run the following query:
```sql
SELECT *
FROM imdb.aka_title
WHERE title LIKE '%(none)%'
```
From the query result, we can see that there are many rows where the parsing of the original file was obviously incorrect.
For example, titles such as `All data and software released by Internet Movie Database  Ltd  is (None)` is not a movie title.
Delete these obviously junk records. They all have the same `movie_id` of 4697912.

With these changes, the foreign key can be added successfully:
```sql
ALTER TABLE aka_title ADD FOREIGN KEY (movie_id) REFERENCES title(id);
```

If you complete all these steps, all foreign keys have been added to the database!

**Comment by alberanid** [comment]
@andrewdbate : exceptional walkthrough, thank you very much.  I've added a link to it in the documentation and your name to the credits.

Thanks!
