### ISSUE TITLE
Missing title

### ISSUE THREAD

**Issue by slef** [alberanid/imdbpy#140]
#### Issue description

In version 6.4.1, get_movie on some movies returns an empty title:

```
>>> import imdb
>>> i = imdb.IMDb()
>>> mm = i.get_movie('6187620')
>>> mm
<Movie id:6187620[http] title:_None_>
```

While the title appears as "Painkillers" on https://www.imdb.com/title/tt6187620/

#### Version of IMDbPY, Python and OS

- **Python:** 3.6.4
- **IMDbPY:** 6.4.1
- **OS:** `('Darwin', 'Stefans-MacBook-Air.local', '17.5.0', 'Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64', 'x86_64', 'i386')`

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python

import imdb
i = imdb.IMDb()
m = i.get_movie('6187620')
print(m['title'])
```

#### What's the expected result?

- `Painkillers`

#### What's the actual result?

```
Traceback (most recent call last):
  File "imdbtest.py", line 4, in <module>
    print(m['title'])
  File "/usr/local/lib/python3.6/site-packages/imdb/utils.py", line 1468, in __getitem__
    rawData = self.data[key]
KeyError: 'title'
```

#### Additional details

- Trying 6.4.1 because the 6.5beta crashes on my system.

**Comment by uyar** [comment]
Now 6.5dev shouldn't crash and this should work. Can you confirm?

**Comment by slef** [comment]
6.5dev no longer crashes, but this problem persists: for `i.get_movie('6187620')` I still get `<Movie id:6187620[http] title:_None_>`.

**Comment by alberanid** [comment]
it was a problem for only in-production title, that are missing release dates and other information.  Should be fixed, now.

**Comment by slef** [comment]
Yes it works!! Thanks a lot.
