### ISSUE TITLE
Problems with cast output

### ISSUE THREAD

**Issue by JohnnyD0101** [alberanid/imdbpy#141]
#### Issue description

The cast output is written twice.

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.6.5rc1
- **IMDbPY:** 6.5dev20180316
- **OS:** Linux Debian 10 x86_64

#### Steps to reproduce the issue

```
#!python

from imdb import IMDb
ia = IMDb()

movie = ia.get_movie(806028)

cast = movie['cast']
print(cast)
```

#### What's the expected result?

- [<Person id:0125367[http] name:_Buttgereit, Jörg_>, <Person id:2268489[http] name:_Citron, Christian_>, <Person id:1845246[http] name:_Haufen, Graf_>, <Person id:2269437[http] name:_Klocker, Marc_>, <Person id:2268338[http] name:_Ruf, Ines_>]

#### What's the actual result?

- [<Person id:0125367[http] name:_Buttgereit, Jörg_>, <Person id:2268489[http] name:_Citron, Christian_>, <Person id:1845246[http] name:_Haufen, Graf_>, <Person id:2269437[http] name:_Klocker, Marc_>, <Person id:2268338[http] name:_Ruf, Ines_>, <Person id:0125367[http] name:_Buttgereit, Jörg_>, <Person id:2268489[http] name:_Citron, Christian_>, <Person id:1845246[http] name:_Haufen, Graf_>, <Person id:2269437[http] name:_Klocker, Marc_>, <Person id:2268338[http] name:_Ruf, Ines_>]

#### Additional details

- It does not matter which movie you take.

**Comment by uyar** [comment]
Can you try with the latest version from git (6.5dev20180401). On my setup, it lists the cast once but includes a bogus entry. I'll look into it shortly.

**Comment by JohnnyD0101** [comment]
Hi,

I think I updated too slowly. I am now on version IMDbPY-6.5.dev20180402 and it looks good.

Thanks.
