### ISSUE TITLE
adultSearch option is broken

### ISSUE THREAD

**Issue by futal** [alberanid/imdbpy#142]
#### `adultSearch` parameters does not seem to work

The examples in [README.adult.rst](imdbpy/docs/README.adult.rst) do not show the expected results. The given link to change adult search settings for your IMDB account is broken ([http://imdb.com/find/preferences?_adult=1](http://imdb.com/find/preferences?_adult=1)).

#### Version of IMDbPY, Python and OS

- **Python: 3.5.3**
- **IMDbPY: 6.4.1**
- **OS: Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64**

#### Steps to reproduce the issue

Execute code samples from [README.adult.rst](imdbpy/docs/README.adult.rst). Result displayed for both `adultSearch=True` and `=False` is:

    "Debbie Does Dallas... Again" (2007) 1675910
    "The Cinema Snob" Debbie Does Dallas (2013) 2698246
    Pauly Does Dallas (1993) 0208347
    "Donnie Loves Jenny" Denny Does Dallas (2016) 5575402
    "King of the Hill" Nancy Does Dallas (2009) 1299878

In particular, the expected porn movie `Debbie Does Dallas (1978) 0077415` does not show.

The link [http://imdb.com/find/preferences?_adult=1](http://imdb.com/find/preferences?_adult=1) leads to a 404 error page.

**Comment by uyar** [comment]
Yes, I've noticed that too. As far as I can see, adult searches don't need cookies (anymore?). Only the "adult=include" clause needs to be added to the URL.

**Comment by alberanid** [comment]
@futal : yes, the included cookie is surely expired, so the account is not actually used.

@uyar : nice finding; the problem is that it doesn't apply to the "normal" title search, but only to the advanced one.  Not sure if we want to switch the page we parse (may be a good idea?)

Test urls:
- http://www.imdb.com/find?q=Rocco+Invades+Poland&s=tt&adult=include
- http://www.imdb.com/search/title?title=Rocco+Invades+Poland&adult=include

**Comment by uyar** [comment]
@alberanid : The advanced search page contains more information such as genres, runtime, rating, cast, and so on. So it could be more useful. On the other hand, it doesn't contain the AKAs that the current find page provides. If you think parsing the advanced search is better, I can start on a parser for it.

**Comment by uyar** [comment]
@alberanid : Or support both searches?
