### ISSUE TITLE
Confusing behavior regarding canonical names for person objects

### ISSUE THREAD

**Issue by uyar** [alberanid/imdbpy#145]
#### Issue description

Regular names are reported in some cases and canonical names in others. For example, the main parser reports names in regular format but the bio parser reports birth names in canonical format. And the main parser seems to do a conversion from regular to canonical format during parsing and then back during reporting.

#### Version of IMDbPY, Python and OS

- **Python:** 3.6.4
- **IMDbPY:** 6.5dev20180401
- **OS:** Linux x86_64

#### Steps to reproduce the issue

```
#!python

>>> from imdb import IMDb
>>> ia = IMDb()
>>> person = ia.get_person('0000210', info=['main'])
>>> person['name']
'Julia Roberts'
>>> person['canonical name']
'Roberts, Julia'
>>> person.data['name']
'Roberts, Julia'
>>> person = ia.get_person('0000210', info=['biography'])
>>> person['birth name']
'Roberts, Julia Fiona'
```

#### What's the expected result?

I believe it would be better if all names would be reported the same way unless a format is explicitly requested.

#### What's the actual result?

Given above.

**Comment by alberanid** [comment]
Agree.  It probably makes sense to stop converting them completely and just use what's provided from thw web site.

**Comment by alberanid** [comment]
I've changed the code to always store the names as they appear on the web site; canonical names (Surname, Name) are still available accessing keys like person['canonical name']
