### ISSUE TITLE
'full-size cover url' key is a very small preview

### ISSUE THREAD

**Issue by futal** [alberanid/imdbpy#146]
#### Issue description

`'full-size cover url'`-key reference a very small image, typically 101x150 pixels. This does not look like full-size. A link to a larger image is expected.

#### Version of IMDbPY, Python and OS

- **Python: 3.5.3**
- **IMDbPY: 6.4.1**
- **OS: Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64**

#### Steps to reproduce the issue

```
>>> the_matrix = ia.get_movie('0133093')
>>> the_matrix['full-size cover url']
'https://ia.media-imdb.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX101_CR0,0,101,150_.jpg'
```

The image is very small: 101x150 pixels. I did not figure out where this URL was extracted from. The image displayed on IMDb is 182x268. A link showing a much larger image is given in the `<head>` section of the html page.

Comparing the different image URLs, you can notice that the end of the URL defines the image size and cropping size. For example in `@._V1_UY1200_CR84,0,630,1200_AL_.jpg`:

 * `V1` has an unknown meaning. You get the same image with `V2`, `V3`, etc.
 * `U` has an unknown meaning. Here it works as well with `S` while other letters seem to deactivate resizing.
 * `Y1200` defines that the poster will be resized to a height of 1200 px. You can define that the poster be resize to a given width with `X` instead of `Y`.
 * `CR84,0,630,1200` defines the cropping area. The last two numbers define the width and height of the resulting image (here the full height of the poster is displayed). The first two numbers define how much the cropping area is shifted to the right/bottom. Shifting to the bottom as a meaning only if the image height is smaller than the original poster height (no meaning here as both are 1200 pixels). Shifting to the right as a meaning only if the image width is smaller than the original poster width (here it has a meaning because the image is 630 pixel wide while the poster would be 798 pixel wide for the selected 1200 pixel height). I have only been able to figure the actual poster width (798 pixel for a 1200 px height) with trials and errors.
 * `AL_` has an unknown meaning. It works without.

It would make sense to link to an image with more pixels, for example 1200 pixel high. However I don't know how to determine the actual poster width for a given height. Here the expected result would:

```
>>> the_matrix = ia.get_movie('0133093')
>>> the_matrix['full-size cover url']
'https://ia.media-imdb.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY1200_CR0,0,798,1200_.jpg'
```

**Comment by Markus-at-GitHub** [comment]
Hi futal,

I solved this problem the following way. In a nutshell: I  take the url and throw everything between '@' and the extension away. Here is an code example:

```
import os
from imdb import IMDb

def url_clean(url):
    base, ext = os.path.splitext(url)
    i = url.count('@')
    s2 = url.split('@')[0]
    url = s2 + '@' * i + ext
    return url

ia = IMDb()
movie = ia.get_movie('3721964')
url = movie['cover']
print(url_clean(url))
```
Do you need more explanation?

Greetings
Markus

**Comment by futal** [comment]
Hi Markus!

That's exactly what I was looking for! It actually works without the file extension: `url = url[:url.rindex('@')+1]` is enough to get the full-size cover URL from the current URL. I think that it should be the actual return value given by imdbpy.

**Comment by Markus-at-GitHub** [comment]
Hi futal,

I am glad I could help.

Your solution ist much more elegant than mine. I am new to Python. I am learning and some day I will get there.

I experimented with lots of urls. There were some which did not work without the extension. So do not be surprised.

Sometimes the urls contained at least two '@'. The download did not work if you reduce the number in the url to only one '@'. But your solution seems to cover that case.

Greetings
Markus

**Comment by alberanid** [comment]
thanks to both @futal and @Markus-at-GitHub : in fact the feature was already there, but the regular expression used was wrong.

I've fixed it.

To get the full-size image, you can access movie['full-size cover url'] (person['full-size headshot'] for persons)

I'm not too happy with the fact that now the full-size image has no extension.  @Markus-at-GitHub : can you provide me an example of url that doesn't work adding the extension?
I'll probably change again the code to always add the extension, if it doesn't break anything.

**Comment by bradpirtle** [comment]
You need to preserve the @'s if there is more than one (for some reason).
The comments suggestions work:

`url = url[:url.rindex('@')+1]`

but the code that was signed in does not: (38aef8e)

` _re_fullsizeURL = re.compile(r'(?<=@).*?$')`

This takes everything from the right of the "first" @, not the "last".

Example with 2 @'s:
http://www.imdb.com/title/tt6624126/
https://ia.media-imdb.com/images/M/MV5BNThmYzMxYmYtMTc3Ny00NTVlLWI1NWQtNmJiNWJhZDBiZDkyXkEyXkFqcGdeQXVyMTAzNDg1MA@@._V1_SY1000_CR0,0,659,1000_AL_.jpg

This gives a 404:
https://ia.media-imdb.com/images/M/MV5BNThmYzMxYmYtMTc3Ny00NTVlLWI1NWQtNmJiNWJhZDBiZDkyXkEyXkFqcGdeQXVyMTAzNDg1MA@

This works (even without the extension):
https://ia.media-imdb.com/images/M/MV5BNThmYzMxYmYtMTc3Ny00NTVlLWI1NWQtNmJiNWJhZDBiZDkyXkEyXkFqcGdeQXVyMTAzNDg1MA@@

I dont have any examples that dont work without extension, but a failsafe fix should probably preserve that.
FYI.

**Comment by alberanid** [comment]
fixed adding the extension and using the proposed code to consider the multiple-@ case.

Thanks!

**Comment by mgolesorkh** [comment]
In some movies, cover URL contains no @.
I just add new rule for 'full-size cover url' in imdb/parser/http/movieParse.py DOMHTMLMovieParser class.

`Rule(
        key='full-size cover url',
            extractor=Path('//link[@rel="image_src"]/@href')
        )`

That works for me.
BR.

**Comment by alberanid** [comment]
@mgolesorkh does it work also for urls that contains @?  Is the result the same you can obtain calling the get_fullsizeURL method of a Movie object?  Can you open a PR?
