### ISSUE TITLE
The "in" operator doesn't work as described in the documentation

### ISSUE THREAD

**Issue by uyar** [alberanid/imdbpy#151]
#### Issue description

The documentation states that "key in movieObject" should indicate whether the key is available for the given movieObject but this doesn't work.

#### Version of IMDbPY, Python and OS

- **Python:** 3.6.4
- **IMDbPY:** 6.5dev20180410
- **OS:** Linux 4.13.0-37-generic #42~16.04.1-Ubuntu SMP x86_64

#### Steps to reproduce the issue

```
#!python

from imdb import IMDb

ia = IMDb()
movie = ia.get_movie('0133093')
print('title' in movie, 'title' in movie.keys())
```

#### What's the expected result?

True True

#### What's the actual result?

False True

**Comment by alberanid** [comment]
Nice catch: the documentation is wrong. :-)
The 'in' operator is used to check if a person has worked in a given movie (and vice-versa).

To check for a key in a movie, the has_key method must be used.

I'm updating the documentation.

**Comment by uyar** [comment]
If I'm not mistaken, has_key has been removed in Python 3 at some point.

**Comment by uyar** [comment]
@alberanid: Oh, OK. I feel like it's not a good practice to use syntax which has been deprecated. How about deriving these classes from MutableMapping?

**Comment by alberanid** [comment]
@uyar : it could make sense to refactor some of the base classes, they are 14 years old, now. ;-)

Basically, they all inherit from imdb.utils._Container (very bad name and place, I agree :)) and the data is stored in a "data" dictionary of the instance.
The \_\_getitem\_\_ method also takes care of some transformation and some aliases for keys.

In fact, we could also merge the behavior of _person in movie_ and _key in movie_: after all, keys are always strings, so it's simple to support both with the same operator.

**Comment by uyar** [comment]
@alberanid: If I understand correctly, you have reservations about using the `in` operator for key checks since it is already used for checking people working in movies. But being accustomed to dictionary syntax, if I'm using `movie['title']` or `movie.get('title')` then I would expect `'title' in movie` to return True. Getting False for this expression is confusing. And I think having to use `has_key` makes it even more confusing. It feels like a strange, deprecated dictionary.

My suggestion would be to derive the `_Container` class (with a new name and place if you like) from `MutableMapping` and have `'title' in movie` return True. For people working in movies, I would prefer something like `reeves in matrix['cast']` or `kubrick in shining['crew']` rather than just `keanu in matrix` but I guess keeping these for backward compatibility makes sense.

**Comment by uyar** [comment]
Not just backward compatibility of course. They might make better sense for most people.

**Comment by alberanid** [comment]
@uyar : I had reservations years ago, but now I totally agree with you: it makes sense for the 'in' operator to work with both persons and keys!

The solution with "kubrick in shining['crew']" is cool, but as you say breaks backward compatibility, so maybe it's a thing we can consider for a future release.

**Comment by alberanid** [comment]
I've introduced https://github.com/alberanid/imdbpy/commit/7ded37d04f8f340eab57c2afec84140045b380b4 to also support the "key in object" syntax.

For the moment I will not do the refactor: feel free to work on that, if you want!

**Comment by uyar** [comment]
Refactoring is not urgent. I think this issue is OK to close.
