### ISSUE TITLE
"TypeError: expected string or bytes-like object" on update()

### ISSUE THREAD

**Issue by guentherh** [alberanid/imdbpy#156]
#### Issue description

Executing the given code results in python and imdbpy crashing and returning the error-message found below

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.5.3
- **IMDbPY:** 6.6dev20180415
- **OS:** ```('Linux', 'raspberrypi', '4.14.30-v7+', '#1102 SMP Mon Mar 26 16:45:49 BST 2018', 'armv7l', '')```

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python

from imdb import IMDb()
ia = IMDb()
the_matrix = ia.get_movie('0133093')
ia.update(the_matrix, ['technical'])
```

#### What's the expected result?

- Update the Movie object with more information

#### What's the actual result?

```2018-05-02 10:28:03,314 ERROR [imdbpy.parser.http.domparser] /home/pi/.local/lib/python3.5/site-packages/imdb/parser/http/utils.py:436: DOMHTMLTechParser: caught exception postprocessing data
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/imdb/parser/http/utils.py", line 433, in parse
    data = self.postprocess_data(data)
  File "/home/pi/.local/lib/python3.5/site-packages/imdb/parser/http/movieParser.py", line 1882, in postprocess_data
    data[key] = [self.re_space.sub(' ', x).strip() for x in data[key]]
  File "/home/pi/.local/lib/python3.5/site-packages/imdb/parser/http/movieParser.py", line 1882, in <listcomp>
    data[key] = [self.re_space.sub(' ', x).strip() for x in data[key]]
TypeError: expected string or bytes-like object```

**Comment by alberanid** [comment]
@guentherh thanks for the report!
Should be fixed in the repository version: technical information are stored in the 'tech' key.
