### ISSUE TITLE
AKAs parser is broken

### ISSUE THREAD

**Issue by alberanid** [alberanid/imdbpy#159]
#### Issue description

The AKAs are not correctly parsed

#### Steps to reproduce the issue

```
#!python

from imdb import IMDb

ia = IMDb()
movie = ia.get_movie(1)
print(movie['akas'])

```

#### What's the expected result?

- a list of aliases

#### What's the actual result?

- ['Carmencita - spanyol tánc\n                            (Hungary)\n                        \n                        \n                            Καρμενσίτα\n                            (Greece)\n                        \n                        \n                            Карменсита\n                            (Russia)']

**Comment by jsynowiec** [comment]
I would like to clarify what is the desired output of `akas`, `akas from release info` and the `release dates`. Why the country/aka/date is glued together by the `::` separator? Why not just return the list of dicts as it's easier to work with?

**Comment by alberanid** [comment]
@jsynowiec good questions, I'm not sure to remember all the details, but...

> what is the desired output of akas, akas from release info and the release dates

Currently, they are list of strings (well, from what I remember).
By the way, "akas from release info" can probably just override "akas", when that page is parsed.

> Why the country/aka/date is glued together by the :: separator?

Historical reasons: a bad choice I made 10/15 years ago when I decided to put the notes about an information in the same string with its value, separated by ::
I'd be ok with changing it with a nicer format; I just wonder how much code out there we would break doing so. :(

> Maybe those raw lists of dicts could be retained under raw akas and raw release dates keys?

It may be an idea; or, if we don't want to break backward compatibility, we can store the new dictionaries values in a different key.

@uyar : do you have any opinion about it?

Thanks!

**Comment by uyar** [comment]
@alberanid @jsynowiec : Personally, I don't like the `::` separated values. They require the application code to do further parsing on the obtained data. Although the `::` splitting is fairly trivial, it feels like a nuisance. I would agree with not breaking backward compatibility and introducing new keys where these components are stored separately. One issue I can think of is this: Currently when you get something like `movie['plot']` the value is in the form `"plot::author"`. Should we put these components into a sub-dict as in `{'plot': {'text': plot, 'author': author}}`, or  two keys at the same level as in `{'plot text': plot, 'plot author': author}`? The first one is more structured but it requires one more level of indexing which feels tiresome to me. The application code might not be interested in the author but will have to pay the price of the extra level anyway.

**Comment by jsynowiec** [comment]
I agree that introducing breaking changes is undesired. That's why I've proposed to add two new keys - `raw akas` and `raw release dates`. They could contain the raw output (lists of dicts) as it's returned from `DOMHTMLReleaseinfoParser`. Those are pretty easy to work with. Much better than the need to further parse the `::` separated strings.

BTW Is splitting countries in [movieParser.py#L1403](https://github.com/alberanid/imdbpy/blob/master/imdb/parser/http/movieParser.py#L1403) needed? Release dates and akas tables seem to contain only single country per row.

**Comment by alberanid** [comment]
closing, since this issue refers to just release dates.

@uyar : in general, I'd prefer keeping the number of levels as low as possible.

@jsynowiec 

> BTW Is splitting countries in movieParser.py#L1403 needed? 

Hmmm it was probably different, years ago.
That's another case of "do the right/clean thing, or preserve backward compatibility?"

I'm not a total fan of backward compatibility: after all this is a small, non-critical, project, but again...
