### ISSUE TITLE
Incomplete list of episodes

### ISSUE THREAD

**Issue by gustaebel** [alberanid/imdbpy#160]
#### Issue description

The list of episodes for a tv series is incomplete, it only contains one season. It seems that only the most recent season is included.

#### Version of IMDbPY, Python and OS

- **Python:** 3.6.5
- **IMDbPY:** 6.6dev20180523
- **OS:** Linux

#### Steps to reproduce the issue

The following code downloads the episode list of "House of Cards" which has 5 seasons, but only the fifth season is contained in the result.

```
#!python
import pprint, imdb

db = imdb.IMDb()
f = db.get_movie("1856010")
db.update(f, "episodes")
pprint.pprint(f["episodes"])
```

**Comment by uyar** [comment]
@gustaebel: The episodes page for a series only contains the latest season by default. Earlier seasons have to selected separately. We can get the data by fetching each season separately but it would be nicer if we could find a page that contains all episodes. The https://www.imdb.com/search/title/?series=tt1856010&count=100 page contains all episodes but doesn't include the chapter and episode numbers. The IMDb mobile app has an "all episodes" page which contains all the necessary data but I couldn't find an external link for it.

**Comment by gustaebel** [comment]
`IMDbHTTPAccessSystem.get_movie_episodes()` does exactly that. It fetches the page for the current season (http://www.imdb.com/title/tt1856010/episodes) and then fetches all remaining season pages after that. But somehow the `_seasons` variable turns out to be an empty list.

From my superficial understanding the code looks fine. `DOMHTMLSeasonEpisodesParser` extracts the list of season numbers from the `<select id="bySeason">` element, but somehow this no longer works.

**Comment by TheophileBlard** [comment]
Hi @gustaebel, I also ran into this problem and I found a very simple hotfix.
Just replace the line : 
_seasons = data_d['data'].get('_seasons') or []
By : 
_seasons = range(1, _current_season)
It might be buggy for some series, and it does not solve the problem (coming from the parser), but you will get a dictionary with all seasons (I tested it)

**Comment by uyar** [comment]
I've applied a patch for this. Please reopen the issue if I've overlooked something.

**Comment by Prosfilaes** [comment]
Running the code in the first message gives me this; apparently this bug is back?

{5: {1: <Movie id:5419058[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 53 (2017)_>,
     2: <Movie id:5965956[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 54 (2017)_>,
     3: <Movie id:6010608[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 55 (2017)_>,
     4: <Movie id:6059620[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 56 (2017)_>,
     5: <Movie id:6110792[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 57 (2017)_>,
     6: <Movie id:6411836[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 58 (2017)_>,
     7: <Movie id:6411844[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 59 (2017)_>,
     8: <Movie id:6411838[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 60 (2017)_>,
     9: <Movie id:6411842[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 61 (2017)_>,
     10: <Movie id:6411846[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 62 (2017)_>,
     11: <Movie id:6411854[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 63 (2017)_>,
     12: <Movie id:6411858[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 64 (2017)_>,
     13: <Movie id:6411862[http] title:_"House of Cards (TV Series 2013–2018)" Chapter 65 (2017)_>}}

**Comment by uyar** [comment]
@Prosfilaes I can't reproduce this. Using both a regular IMDbPY install from PyPI or from the current repository, I get six seasons. What Python and IMDbPY versions are you using?

**Comment by Prosfilaes** [comment]
Sorry; I think I messed up on which version/copy of IMDbPY I was using. I've got it working now.
