### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Pechi77** [alberanid/imdbpy#164]
#### Issue description

*Can we get movie id by giving movie name as input??*

#### Version of IMDbPY, Python and OS

- **Python:** `python 3.6`
- **IMDbPY:** `'6.5'`
- **OS:** `uname_result(system='Windows', node='Lenovo', release='10', version='10.0.17134', machine='AMD64', processor='AMD64 Family 22 Model 48 Stepping 1, AuthenticAMD'))`

**Comment by alberanid** [comment]
well, IMDbPY is decently documented, I would say...

The safest way is to do a search and get the movieID of the first result:

    #!/usr/bin/env python3
    # -*- coding: utf-8 -*-
    
    from imdb import IMDb
    
    ia = IMDb()
    results = ia.search_movie('The Matrix')
    if results:
        movie = results[0]
        print(movie.movieID)

There's another option, but it assumes that you know the **exact** title as used by IMDb to uniquely identify movies, and this may not work all the times:

    movieID = ia.title2imdbID('The Matrix (1999)')
    print(movieID)
