### ISSUE TITLE
movie.asXML() is producing not valid xml

### ISSUE THREAD

**Issue by antonioforte** [alberanid/imdbpy#172]
#### Issue description

The xml output from movie.asXML() is not parseable by python xml.etree.ElementTree.

#### Version of IMDbPY, Python and OS

Python 3.6.4
imdbpy 6.6dev20180708
Windows 7

#### Steps to reproduce the issue
    #!python

    import xml.etree.ElementTree as ET
    import imdb
    import io

    ia = imdb.IMDb()
    search_results = ia.search_movie('The Godfather')

    if search_results:
        movieID = search_results[0].movieID
        movie = ia.get_movie(movieID)
        if movie:
            xml = io.StringIO(movie.asXML())
            
            # Uncomment this to print xml string to console.
            # print(xml.getvalue())

            try:
                ET.fromstring(xml.getvalue())
            except ET.ParseError as e:
                print('Problems parsing xml string', e)
            else:
                print('Xml output is good')

#### What's the expected result?

Xml output is good

#### What's the actual result?

Problems parsing xml string

#### Additional details

Some examples of how the xml keys end up

<('smart-long-imdb-canonical-title',-'ascii',-'ignore') key="smart long imdb canonical title">Godfather, The (1972)</('smart-long-imdb-canonical-title',-'ascii',-'ignore')>

<('cast',-'ascii',-'ignore') key="cast" infoset="main">

**Comment by alberanid** [comment]
thanks for the report!

The bug should be fixed in the repository version.
