### ISSUE TITLE
The xml output from movie.asXML() is not parseable by python xml.etree.ElementTree.

### ISSUE THREAD

**Issue by antonioforte** [alberanid/imdbpy#174]
#### Issue description

The xml output from movie.asXML() is not parseable by python xml.etree.ElementTree.
Note: this is similar to [issue ](https://github.com/alberanid/imdbpy/issues/172)
The only diference is that i added:

    ia.update(movie, info='all')

#### Version of IMDbPY, Python and OS

Python 3.6.4
imdbpy 6.6dev20180715c
Windows 7

#### Steps to reproduce the issue
    #!python
    import xml.etree.ElementTree as ET
    import imdb
    import io

    ia = imdb.IMDb()
    search_results = ia.search_movie('The Godfather')

    if search_results:
        movieID = search_results[0].movieID
        movie = ia.get_movie(movieID)
        if movie:
            # Without the update everything goes smoothly
            ia.update(movie, info='all')

            xml = io.StringIO(movie.asXML())

            # Uncomment this to print xml string to console.
            # print(xml.getvalue())

            try:
                ET.fromstring(xml.getvalue())
            except ET.ParseError as e:
                print('Problems parsing xml string', e)
            else:
                print('Xml output is good')

            # with open('movie.xml', 'w', encoding='utf-8') as stream:
            #    stream.write(xml.getvalue())

#### What's the expected result?

Xml output is good

#### What's the actual result?
    Traceback (most recent call last):
      File "K:/Dev/python/scripts/Collector data/misc/imdbpy-test-xml-output.py", line 15, in <module>
        xml = io.StringIO(movie.asXML())
      File "C:\Python\3.6.4\lib\site-packages\imdb\utils.py", line 1473, in asXML
        value = self.getAsXML(key, _with_add_keys=_with_add_keys)
      File "C:\Python\3.6.4\lib\site-packages\imdb\utils.py", line 1463, in getAsXML
        fullpath=tag))
      File "C:\Python\3.6.4\lib\site-packages\imdb\utils.py", line 1075, in _seq2xml
        fullpath='%s.%s' % (fullpath, tagName))
      File "C:\Python\3.6.4\lib\site-packages\imdb\utils.py", line 1099, in _seq2xml
        fullpath='%s.%s' % (fullpath, tagName))
      File "C:\Python\3.6.4\lib\site-packages\imdb\utils.py", line 1075, in _seq2xml
        fullpath='%s.%s' % (fullpath, tagName))
      File "C:\Python\3.6.4\lib\site-packages\imdb\utils.py", line 1110, in _seq2xml
        charactersRefs=charactersRefs))
      File "C:\Python\3.6.4\lib\site-packages\imdb\utils.py", line 922, in _normalizeValue
        value = _handleTextNotes(escape4xml(value))
      File "C:\Python\3.6.4\lib\site-packages\imdb\utils.py", line 872, in escape4xml
        value = _re_amp.sub('&amp;', value)
    TypeError: expected string or bytes-like object

#### Additional details

I have determined that a None value is being passed to: 

    imdb.utils.escape4xml

So, i tried this to account for the None value passed:

    #!python
    def escape4xml(value):
        """Escape some chars that can't be present in a XML value."""
        if isinstance(value, (int, float)):
            value = str(value)
        if not value:
            value = 'wierd'
        value = _re_amp.sub('&amp;', value)
        value = value.replace('"', '&quot;').replace("'", '&apos;')
        value = value.replace('<', '&lt;').replace('>', '&gt;')
        if isinstance(value, bytes):
            value = value.decode('utf-8', 'xmlcharrefreplace')
        return value

With the changed method in place the call to movie.asXML() succeds but it is still not valid XML.

Here are some examples of the produced xml:

    <writers infoset="main">
        <person id="0701374"><name>Mario Puzo</name><notes>(screenplay by)</notes></person>
        <person id="0000338"><name>Francis Ford Coppola</name><notes>(screenplay by)</notes></person>
        <person><name>wierd</name></person>
        <person id="0701374"><name>Mario Puzo</name><notes>(based on the novel by)</notes></person>
    </writers>

    <item key="Non so più ">
        <(cherubino's-aria)-from-opera-"le-nozze-di-figaro"-act-i,-scene-v-music-by key="(cherubino&apos;s aria) from opera &quot;le nozze di figaro&quot; act i, scene v music by">Wolfgang Amadeus Mozart </(cherubino's-aria)-from-opera-"le-nozze-di-figaro"-act-i,-scene-v-music-by>
        <libretto-by key="libretto by">Lorenzo da Ponte</libretto-by>
    </item>

**Comment by alberanid** [comment]
@antonioforte thanks for the report!

It should now be fixed, even if I'm not completely sure it may not happen again with other movies (that part should be refactored heavily...)

**Comment by antonioforte** [comment]
Many thanks for fixing this.

I will report if it happens on other movies.
I forgot to say that this not happen on the old sql or the s3 modes.

Happy movies(or not)!!!
