### ISSUE TITLE
Movie returned from old sql access system only returns 1 cast member

### ISSUE THREAD

**Issue by antonioforte** [alberanid/imdbpy#176]
#### Issue description

This happens when using the sql access system.
The movie['cast'] only returns 1 person. This person.currentRole includes all the roles in the movie.

#### Version of IMDbPY, Python and OS

- **Python:** - Python 3.6.4
- **IMDbPY:** - 6.6dev20180715c
- **OS:** windows 7

#### Steps to reproduce the issue

    #!python
    import imdb

    dburi = 'sqlite:///C:\\IMDB data\\imdb_list_files.db'

    ia = imdb.IMDb('sql', uri=dburi)
    results = ia.search_movie('The Godfather')

    if results:
        for result in results:
            ia.update(result, info='main')
            if 'director' in result.keys():
                names = [d.get('name', '') for d in result['director']]
                if 'Francis Ford Coppola' in names:

                    cast = result.get('cast', [])
                    print('Len cast', len(cast))

                    for person in cast:
                        print(':::::::::::::::::::::::::::::::::::::::::::::::')
                        print(person.get('name', ''), '::', person.currentRole)

#### What's the expected result?

- The cast of the movie should have more persons and the person.currentRole
should not have so many roles.

#### What's the actual result?

    Len cast 1
    :::::::::::::::::::::::::::::::::::::::::::::::
    Chris Anastasio :: Policeman / Luca Brasi's Assassin / Cuneo / Don Vito Corleone / Extra in Furniture-Moving Scene / Neri / Sonny Corleone / Clemenza / Fredo / Calo - Sicilian Sequence / Barzini / Piano Player in Montage / Baptism Observer / Boy on Street Who Attended Funeral / Bonasera / Don Victor Stracci / Crowd / Tom Hagen / Tom Hagen's Son / Cowboy on the Set at Woltz's Studio / Don Tommasino - Sicilian Sequence / Usher in Bridal Party / Bruno Tattaglia / Anthony Vito Corleone / Sonny's Bodyguard / Cop Outside Hospital / Don Zaluchi / Capt. McCluskey / Fabrizio - Sicilian Sequence / Toll Both Collector / Sonny's Killer #1 / Tony - Stablehand / Singer / Sollozzo / Wedding Guest /  / Jack Woltz / Boy at Wedding / Johnny Fontane / Paulie Gatto / Corleone Family Member / Priest at Baptism / Luca Brasi / Michael Corleone / Lou - Sollozzo's Driver / Pallbearer / Philip Tattaglia / Floral Designer / Drunk / Narrator of Theatrical Trailer / Moe Greene / Rocco Lampone / Mobster at Funeral with Barzini / Carlo / Nazorine / Street Extra / Willi Cicci / Enzo the Baker / Vitelli - Sicilian Sequence / Wedding Party Guest / Wedding Guest / Extra in Hospital Scene / Tessio / Clemenza's Son / Fruit Vendor / Dancer in Wedding Scene / Extra in Wedding Scene / Michael Francis Rizzi / Sandra Corleone / Kay Adams / Mama Corleone / Lucy Mancini / Theresa Hagen / Night Nurse / Mrs. Clemenza / Connie / Extra in Wedding Scene / Apollonia - Sicilian Sequence

#### Additional details

- I have been fiddling with the code and i think the problem is in imdb.parser.sql.merge_roles.
The cast members are not being appended to the new_list.

**Comment by alberanid** [comment]
Thanks for the report.

Affecting only the old plain text dataset that is no longer updated, I'd be glad to receive patches (that do not involve or deeply affect the rest of the code), but I fear I'll be not able to devote time to it.

(plus, in this case, it involves Characters, a concept that IMDb has removed completely and will probably be phased out also from IMDbPY at some point in the future)

Thanks!

**Comment by antonioforte** [comment]
Hi alberanid.

So i have come up with some code that seems to have fixed the issue.
I think the code is OK. If you want i can try to change it.

I would like to clarify that i am not really interested in getting Character classes.

I only changed the imdb.parser.sql.merge_roles method.

Unfortunately  i do not know how to use git properly so it is difficult for me to provide
a patch. Maybe now is a good time to learn. Could you do it? The code is below.

This is the changed imdb.parser.sql.merge_roles method.

    def merge_roles(mop):
        """Merge multiple roles."""
        new_list = []
        for m in mop:
            m_isinnewlist = False
            m_indexinnewlist = None
            if isinstance(m, Person):
                for i, person in enumerate(new_list):
                    if person.isSamePerson(m):
                        m_isinnewlist = True
                        m_indexinnewlist = i
                        break
            else:
                if m in new_list:
                    m_isinnewlist = True
                    m_indexinnewlist = new_list.index(m)

            if m_isinnewlist:
                keep_this = new_list[m_indexinnewlist]
                if not isinstance(keep_this.currentRole, list):
                    keep_this.currentRole = [keep_this.currentRole]
                keep_this.currentRole.append(m.currentRole)
            else:
                new_list.append(m)
        return new_list


A simple test. The person named Milla Jovovich plays 2 roles
in some of the movies returned.

    import imdb


    dburi = 'sqlite:///C:\\IMDB data\\imdb_list_files.db'

    ia = imdb.IMDb('sql', uri=dburi)
    results = ia.search_movie('Resident Evil: The Final Chapter')

    if results:
        for result in results:
            ia.update(result, info='main')
            if 'director' in result.keys():
                names = [d.get('name', '') for d in result['director']]
                if 'Paul W.S. Anderson' in names:

                    print('*'*78)
                    print(result)

                    cast = result.get('cast', [])
                    print('Len cast', len(cast))

                    for person in cast:
                        print(person.get('name', ''), '::', person.currentRole)
 

Thank you for your attention.

**Comment by alberanid** [comment]
@antonioforte thanks!  I've applied your code on the repository version.

Talking about Git, if you understand Italian, I wrote a short tutorial: https://github.com/raspibo/git-crash-course

Otherwise, these are some good guides and resources:
* https://git-scm.com/book/en/v2
* https://git-scm.com/docs
* https://learngitbranching.js.org/
* https://www.atlassian.com/git/tutorials/learn-git-with-bitbucket-cloud
* https://guides.github.com/introduction/flow/
