### ISSUE TITLE
More flaky tests

### ISSUE THREAD

**Issue by dvzrv** [alberanid/imdbpy#177]
#### Issue description

Currently, during python3.7 rebuilds for Arch Linux, I see more broken tests

#### Version of IMDbPY, Python and OS

- **Python:** 3.7
- **IMDbPY:** 6.5
- **OS:** Arch Linux

#### Steps to reproduce the issue

```
python setup.py build
export PYTHONPATH=${srcdir}/${pkgname}-${pkgver}/build:${PYTHONPATH}
py.test
```

#### What's the expected result?

- All tests succeed

#### What's the actual result?

- Some tests fail.

#### Additional details

```
============================= test session starts ==============================
platform linux -- Python 3.7.0, pytest-3.6.3, py-1.5.4, pluggy-0.6.0
rootdir: /build/python-imdbpy/src/python-imdbpy-6.5, inifile:
plugins: cov-2.5.1
collected 157 items

tests/test_http_chart_bottom.py ...                                      [  1%]
tests/test_http_chart_top.py .....                                       [  5%]
tests/test_http_company_main.py .                                        [  5%]
tests/test_http_gather_refs.py .                                         [  6%]
tests/test_http_movie_combined.py ..............ss..............ss...... [ 30%]
....................ss............................                       [ 62%]
tests/test_http_movie_keywords.py ..                                     [ 63%]
tests/test_http_movie_plot.py ...                                        [ 65%]
tests/test_http_movie_reviews.py .                                       [ 66%]
tests/test_http_movie_sites.py .                                         [ 66%]
tests/test_http_movie_taglines.py F..                                    [ 68%]
tests/test_http_movie_votes.py ....F.                                    [ 72%]
tests/test_http_person_bio.py ..F.F.........F...                         [ 84%]
tests/test_http_person_main.py ......                                    [ 87%]
tests/test_http_person_otherworks.py ...                                 [ 89%]
tests/test_http_search_company.py .                                      [ 90%]
tests/test_http_search_keyword.py ....                                   [ 92%]
tests/test_http_search_movie.py .F.....                                  [ 97%]
tests/test_http_search_movie_keyword.py ...                              [ 99%]
tests/test_http_search_person.py .                                       [100%]

=================================== FAILURES ===================================
____________ test_movie_taglines_single_should_be_a_list_of_phrases ____________

movie_taglines = <function movie_taglines.<locals>.retrieve at 0x7f4469627f28>

    def test_movie_taglines_single_should_be_a_list_of_phrases(movie_taglines):
        page = movie_taglines('if....')
        data = parser.parse(page)['data']
>       assert data['taglines'] == ['Which side will you be on?']
E       assert ['Which side ...ilm Festival'] == ['Which side will you be on?']
E         Left contains more items, first extra item: 'Winner "Best Film" Cannes Film Festival'
E         Use -v to get the full diff

tests/test_http_movie_taglines.py:21: AssertionError
_________________ test_movie_ratings_demographics_should_be_19 _________________

movie_ratings = <function movie_ratings.<locals>.retrieve at 0x7f4469627510>

    def test_movie_ratings_demographics_should_be_19(movie_ratings):
        page = movie_ratings('matrix')
        data = parser.parse(page)['data']
>       assert len(data['demographics']) == 19
E       AssertionError: assert 18 == 19
E        +  where 18 = len({'aged 18 29': {'rating': 8.6, 'votes': 391694}, 'aged 30 44': {'rating': 8.8, 'votes': 529555}, 'aged 45 plus': {'rating': 8.5, 'votes': 113536}, 'aged under 18': {'rating': 8.4, 'votes': 2120}, ...})

tests/test_http_movie_votes.py:45: AssertionError
___________________ test_birth_date_should_be_in_ymd_format ____________________

person_bio = <function person_bio.<locals>.retrieve at 0x7f446975dd90>

    def test_birth_date_should_be_in_ymd_format(person_bio):
        page = person_bio('fred astaire')
        data = parser.parse(page)['data']
>       assert data['birth date'] == '1899-5-10'
E       KeyError: 'birth date'

tests/test_http_person_bio.py:35: KeyError
___________________ test_death_date_should_be_in_ymd_format ____________________

person_bio = <function person_bio.<locals>.retrieve at 0x7f446975dd90>

    def test_death_date_should_be_in_ymd_format(person_bio):
        page = person_bio('fred astaire')
        data = parser.parse(page)['data']
>       assert data['death date'] == '1987-6-22'
E       KeyError: 'death date'

tests/test_http_person_bio.py:47: KeyError
_______________________ test_trade_mark_should_be_a_list _______________________

person_bio = <function person_bio.<locals>.retrieve at 0x7f446975dd90>

    def test_trade_mark_should_be_a_list(person_bio):
        page = person_bio('julia roberts')
        data = parser.parse(page)['data']
>       assert len(data['trade mark']) == 2
E       AssertionError: assert 3 == 2
E        +  where 3 = len(['Her bright smile', 'Gentle voice', 'Her mole.'])

tests/test_http_person_bio.py:107: AssertionError
________ test_found_many_result_should_contain_correct_number_of_movies ________

search_movie = <function search_movie.<locals>.retrieve at 0x7f44695ff730>

    @mark.fragile
    def test_found_many_result_should_contain_correct_number_of_movies(search_movie):
        page = search_movie('ace in the hole')
        data = parser.parse(page)['data']
>       assert 185 < len(data) < 200
E       AssertionError: assert 200 < 200
E        +  where 200 = len([('0043338', {'kind': 'movie', 'title': 'Ace in the Hole', 'year': 1951}), ('1441232', {'kind': 'tv movie', 'title': '...tle': 'Ace in the Hole', 'year': 2015}), ('0149583', {'kind': 'short', 'title': 'Ace in the Hole', 'year': 1942}), ...])

tests/test_http_search_movie.py:30: AssertionError
============== 6 failed, 145 passed, 6 skipped in 107.08 seconds ===============

```

**Comment by dvzrv** [comment]
Ideally, none of the type tests should rely on any hardcoded data.

e.g. `test_movie_taglines_single_should_be_a_list_of_phrases` should check for size greater than whatever

Is  `test_movie_ratings_demographics_should_be_19` supposed to test the amount of something? This does not make any sense, as it might change. A type check would probably be more useful.

Guess something got changed for `test_birth_date_should_be_in_ymd_format` in the API breaking this. Again, here it doesn't make any sense to test against static data. Testing against a validated string or something would make more sense (e.g. are there four digits, a dash, two digits, a dash, two digits?).

`test_trade_mark_should_be_a_list` should not test against static data either, but rather check if it is a list type and or greater 0 (but even that would not be smart). Test name implies this is a test for type list, whereas it tests the amount of objects in a list.

In `test_found_many_result_should_contain_correct_number_of_movies` there are more tests against static numbers. This will break constantly and doesn't make sense for reproducibility and also doesn't help with testing the library really.

**Comment by uyar** [comment]
@dvzrv Most -if not all- of these tests are already fixed in the repo. There are some new failures, I will look into those soon.

You're right about the type tests checking for the value of the data but that's more a problem on the naming of the test function rather than the purpose of the test. For example the function `test_movie_taglines_single_should_be_a_list_of_phrases` wants to make sure that if a movie has one tagline, it is still stored as a list of strings and not directly as a string.

Or the function `test_found_many_result_should_contain_correct_number_of_movies` wants to check that if the search produces multiple results, but still less than the IMDb limit of 200, the list will contain correct number of results. So there are three cases for such searches: 1 result, >200 results, and this one. It's possible that the search for this case produces <200 results today but will produce >200 results tomorrow but I don't think the test is useless.

The demographics test with the explicit reference to the number 19 was due to my misguided belief that IMDb had 19 fixed demographic categories, and the test was modified in https://github.com/alberanid/imdbpy/commit/9dc51779c3c7d48fdc02f3765360ad62d24dcdc9.

I've tried marking test cases where the data is subject to change as "fragile" but a smarter way of handling these would be very nice.

**Comment by dvzrv** [comment]
I see. I'll disable the failing tests then for now, so we can continue with the rebuilds.
Thanks for the clarifications!

I understand, that these types of tests are not easy. Maybe the flaky ones can be set to be allowed to fail?

**Comment by alberanid** [comment]
thanks, I'll try to release a new version as soon as possibile, so that the released version is more up-to-date!

**Comment by uyar** [comment]
@alberanid There are a few tests failing. I can look at them on Monday to see whether it's the test data or the code. Can you hold off the release till then?

**Comment by dvzrv** [comment]
Then there is this one failing, out of nowhere all of a sudden:

```
============================= test session starts ==============================
platform linux -- Python 3.7.0, pytest-3.6.3, py-1.5.4, pluggy-0.6.0
rootdir: /build/python-imdbpy/src/python-imdbpy-6.5, inifile:
plugins: cov-2.5.1
collected 151 items

tests/test_http_chart_bottom.py ...                                      [  1%]
tests/test_http_chart_top.py .....                                       [  5%]
tests/test_http_company_main.py F                                        [  5%]
tests/test_http_gather_refs.py .                                         [  6%]
tests/test_http_movie_combined.py ..............ss..............ss...... [ 31%]
....................ss............................                       [ 64%]
tests/test_http_movie_keywords.py ..                                     [ 66%]
tests/test_http_movie_plot.py ...                                        [ 68%]
tests/test_http_movie_reviews.py .                                       [ 68%]
tests/test_http_movie_sites.py .                                         [ 69%]
tests/test_http_movie_taglines.py ..                                     [ 70%]
tests/test_http_movie_votes.py .....                                     [ 74%]
tests/test_http_person_bio.py ...............                            [ 84%]
tests/test_http_person_main.py ......                                    [ 88%]
tests/test_http_person_otherworks.py ...                                 [ 90%]
tests/test_http_search_company.py .                                      [ 90%]
tests/test_http_search_keyword.py ....                                   [ 93%]
tests/test_http_search_movie.py ......                                   [ 97%]
tests/test_http_search_movie_keyword.py ...                              [ 99%]
tests/test_http_search_person.py .                                       [100%]

=================================== FAILURES ===================================
_____________________ test_name_should_not_include_country _____________________

company_main_details = <function company_main_details.<locals>.retrieve at 0x630282c5af28>

    def test_name_should_not_include_country(company_main_details):
        page = company_main_details('pixar')
        data = parser.parse(page)['data']
>       assert data['name'] == 'Pixar Animation Studios'
E       KeyError: 'name'

tests/test_http_company_main.py:21: KeyError
============== 1 failed, 144 passed, 6 skipped in 116.27 seconds ===============
```

@alberanid could you maybe set this project up in travis? As you're already using tox you can test this library continuously without effort (and for every pull request). Additionally, you would be more on top of things, as these tests break reproducible builds for every downstream!

**Comment by alberanid** [comment]
@uyar : sure, I also wanted to fix a bug or two before the release, so I'll probably wait until the next weekend.

@dvzrv : I'll look at Travis CI integration, good idea, thanks!

**Comment by alberanid** [comment]
if I've not done something (too) wrong, Travis CI can be found here: https://travis-ci.org/alberanid/imdbpy

**Comment by uyar** [comment]
How are Travis builds going to be affected by the IMDb page cache for the tests? It needs to be wiped from time to time, or completely disabled.

**Comment by uyar** [comment]
@dvzrv The company name test that started failing is because the IMDb changed their markup. The URL also redirects to pro.imdb.com now. I've updated the code. I think, unfortunately Travis can not help much with this kind of problem.

**Comment by uyar** [comment]
@alberanid Now all tests are passing except for the XML test under Python 2.7.

**Comment by dvzrv** [comment]
@uyar sure travis won't "fix" your problem, but with it you'll get more continuous feedback, that you can use to counteract with releasing a bugfix version either for the tests or your code.
IMDB is a moving target sadly ;-)

**Comment by uyar** [comment]
@dvzrv Sure Travis is fine and helpful. What I meant was that *in this case* it can't alert me that something has changed on the IMDb side.

@alberanid As I said -if I'm not overlooking something- we need to clear the page cache every once in a while for Travis. Otherwise, if the IMDb markup changes, Travis will check the code against the old markup. Disabling the cache completely doesn't make sense because it would cause pages to be re-fetched for every test case (multiple times during even the same test run). We could either clear the cache per session, or if a certain period has passed since the last time (1 day, 1 week, etc.). The former is easier to implement, the latter is more considerate to IMDb. But the tests aren't retrieving too many pages, so maybe it's not a big deal.

**Comment by uyar** [comment]
@alberanid I didn't know that about Travis. It makes sense when I think about it. If we can also schedule periodic builds, Travis **can** inform us about changes on IMDb then, right?

**Comment by alberanid** [comment]
closing this issue. 

@uyar : Travis is run each day, plus each time a new commit is made.
The committer (and the author) of the commit are notified, but only if they are registered on https://travis-ci.org/ (there is nothing else to do but "Sign in with Github").

I'm not completely sure if emails are sent in case a daily test fails; at the moment I've configured .travis.yml it so that only failures are ever notified).
