### ISSUE TITLE
Mini biography not extracted

### ISSUE THREAD

**Issue by shaljam** [alberanid/imdbpy#178]
#### Issue description
`DOMHTMLBioParser` doesn't parse `mini biography`.

#### Version of IMDbPY, Python and OS

- **Python:** `Python 3.6.5`
- **IMDbPY:** `6.5`
- **OS:** `macOS 10.13.6 (17G65)`

#### Steps to reproduce the issue
```
from imdb import IMDb

p = ia.get_person('2874224')
print(p.get('mini biography'))
```

#### What's the expected result?

- Something like `Anita Perry was born on May 5, 1952 in the USA as Mary Anita Thigpen. She has been married to Rick Perry since 1982. They have two children.` 

#### What's the actual result?
- Empty

#### Additional details

- Link to person: https://www.imdb.com/name/nm2874224/bio

**Comment by alberanid** [comment]
thanks for the report!  Should be fixed in the repository version.
