### ISSUE TITLE
No module named imdb

### ISSUE THREAD

**Issue by floflo2607** [alberanid/imdbpy#181]
#### Issue description

No module named imdb

#### Version of IMDbPY, Python and OS

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
Python 2.7.10

- **IMDbPY:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`
4.7

- **OS:** `python -c 'import platform ; print(platform.uname())'`
('Windows', 'Annie', '8', '6.2.9200', 'AMD64', 'Intel64 Family 6 Model 55 Stepping 8, GenuineIntel')

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python
from imdb import IMDb

# create an instance of the IMDb class
ia = IMDb()

# get a movie
movie = ia.get_movie('0133093')

# print the names of the directors of the movie
print('Directors:')
for director in movie['directors']:
    print(director['name'])

# print the genres of the movie
print('Genres:')
for genre in movie['genres']:
    print(genre)

# search for a person name
people = ia.search_person('Mel Gibson')
for person in people:
   print(person.personID, person['name'])
```

#### What's the actual result?

- Traceback (most recent call last):
  File "C:\Users\Portable\Desktop\Bimovieo\imdb\absorber.py", line 1, in <module>
    from imdb import IMDb
ImportError: No module named imdb

**Comment by alberanid** [comment]
Hi @floflo2607 , I can see a couple of problems.

First: you are using Python 2.7 for your code (absorber.py), but you have installed IMDbPY only on Python 3

Second: the version of IMDbPY you have installed is really old (4.7 - we are now at 6.6)

Please try installing the latest version from the repository or using pip (**pip install imdbpy**)

I'm closing this issue; feel free to reopen it if you found something else.

**Comment by vpolimenov** [comment]
@alberanid 
I have this on the conda env: 
`IMDbPY==6.7.dev20181113`
but it still doesn't work:
`ModuleNotFoundError: No module named 'imdb'`

**Comment by vpolimenov** [comment]
The reason for this was that jupyter wasn't sat up to work in the environment. https://github.com/jupyter/notebook/issues/2359#issuecomment-291114172
