### ISSUE TITLE
Box office info not available

### ISSUE THREAD

**Issue by tijlk** [alberanid/imdbpy#182]
#### Issue description

Even though box office information is available on most IMDb movie pages, no information set in imdbpy seems to contain this information. Am I missing something? Or is it really not there? Why not?

#### Version of IMDbPY, Python and OS

- **Python:** 3.6.6
- **IMDbPY:** 6.6
- **OS:** MacOS

**Comment by alberanid** [comment]
Hi @tijlk : yes, at the moment the box office info are not available.  We should add a parser for them in imdb/parser/http/movieParser.py

**Comment by enriqueav** [comment]
Hi @alberanid. I can work on this. In fact I almost have it ready. I'm just not sure what is the best way to return the values.
Each movie can contain from 0 to many lines of "Box Office" information. Each line contains a title, such as 
- Budget
- Opening Weekend United States
- Cumulative Worldwide Gross

And a value, like 

- $27,788,331, 04 Apr 1999
- $463,517,383

I guess the easiest would be to return as a composite string (joined by '::')

```
>>> for info in matrix['box office']:
...     print(type(info), info)
... 
<class 'str'> Budget::$63,000,000 (estimated)
<class 'str'> Opening Weekend United States::$27,788,331, 04 Apr 1999
<class 'str'> Cumulative Worldwide Gross::$463,517,383
>>> for info in avatar['box office']:
...     print(type(info), info)
... 
<class 'str'> Budget::$237,000,000 (estimated)
<class 'str'> Opening Weekend United Kingdom::GBP8,509,050, 20 Dec 2009
<class 'str'> Cumulative Worldwide Gross::$2,787,965,087, 13 Feb 2015
>>> 
```

What do you think?

**Comment by alberanid** [comment]
@enriqueav : cool, thanks!

As you prefer... in the end the important is to have the data.

Lately we tend to avoid the "strings::with::separator" format and move to structured dictionaries.
So, something like: `{'budget': '$237,000,000 (estimated)', 'Opening Weekend United Kingdom': '...', ...}` would be great (obviously, no key if the information is missing), but as said... as you prefer.

Thanks!

**Comment by enriqueav** [comment]
I guess I did not reference this issue correctly in the PR
https://github.com/alberanid/imdbpy/pull/212
Which is merged now

**Comment by alberanid** [comment]
no prob, closing this now. Thanks!

**Comment by alberanid** [comment]
@enriqueav : by the way, if you plan to do more work on IMDbPY, I'd be glad to add you to the list of developers of the Github project. Let me know.

**Comment by enriqueav** [comment]
@alberanid sounds good... but what exactly does it mean to be added to the developers list?

**Comment by alberanid** [comment]
@enriqueav well, not much. You gain access to push to the repository, but in general is always better to work following the fork workflow (so you work on your fork, create a PR and someone else merge it). Besides this, you can assign yourself to the issues you'll work on, review the sporadic pull requests and so on.
Obviously no minimum level of work is expected: everything is up to you depending on your time and interest.
(as said: it doesn't really change much, so if you prefer to contribute like you're doing now, that's also ok)
