### ISSUE TITLE
problem while parsing

### ISSUE THREAD

**Issue by floflo2607** [alberanid/imdbpy#183]
#### Issue description

*write the description here*

#### Version of IMDbPY, Python and OS

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
3.5.3
- **IMDbPY:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`
6.6
- **OS:** `python -c 'import platform ; print(platform.uname())'`
SMP Debian 4.9.110-3+deb9u2 (2018-08-13) , machine='x86_64', processor=''

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python
from imdb import IMDb
ia = IMDb()
fichier=open("movielst.txt","w")
num,num2=1,'0000001'
movie = ia.get_movie(num2)
fichier.write(str(movie.get('title'))+'/'+str(movie.get('Votes')))
```

#### What's the expected result?

- write the title and the votes in the .txt

#### What's the actual result?

-File "blabla.py", line 20 
SyntaxError: unexpected EOF while parsing

#### Additional details

- it's a virtual box which use Oracle VM

**Comment by alberanid** [comment]
> -File "blabla.py", line 20
> SyntaxError: unexpected EOF while parsing

You have a syntax error on line 20 of file blabla.py.

**Comment by floflo2607** [comment]
There less than 20 lines of code

**Comment by alberanid** [comment]
that code works (beside the fact that it's 'votes' and not 'Votes'); I'm quite sure you're running a different script.

```
$ cat t.py 
from imdb import IMDb
ia = IMDb()
fichier=open("movielst.txt","w")
num,num2=1,'0000001'
movie = ia.get_movie(num2)
fichier.write(str(movie.get('title'))+'/'+str(movie.get('votes')))


$ python3 ./t.py


$ cat movielst.txt 
Carmencita/1403
```

**Comment by floflo2607** [comment]
ok thanks
