### ISSUE TITLE
Add votes to the default keywords in filmography dictionary

### ISSUE THREAD

**Issue by athoag** [alberanid/imdbpy#186]
#### Issue description

I am trying to sort a person's filmography by votes. I want to do this quickly (on the order of ~1 sec or less) because I am writing an interactive program. Currently, the filmography dictionary retrieved for a person is provided as a list of Movie() objects, which have limited information, e.g.:

`
[u'kind',
 u'title',
 u'year',
 u'canonical title',
 u'long imdb title',
 u'long imdb canonical title',
 u'smart canonical title',
 u'smart long imdb canonical title']
`

This is opposed to the large dictionary that is retrieved if one issues a `get_movie()` command with the movieID specified.

I have tried to issue an `ia.update()` command to all of the films, perhaps even just using the 'vote details' keyword to cut down the lookup time, but this takes on the order of minutes for a typical actor with ~50 films, even with the limited info lookup. I have also tried to issue a `get_movie()` command to each film in the list using the movieID, which is provided as part of the basic info that comes in the filmography. This similarly takes minutes. 

The only non-default keyword I want is the 'votes' keyword, but it doesn't seem like I can look that up by itself, nor would I expect it to be much faster than the 'vote details' look-up .

A potential solution would be to look up multiple movieIDs in a single http query, but as far as I know the code is not outfitted for this. 

Another potential solution would be to add the 'votes' key to the list of default keys to be included in the movie objects in the filmography dictionary. 

#### Version of IMDbPY, Python and OS

- **Python:**  Python 3.4.5 
- **IMDbPY:** 6.7dev2018081
- **OS:** OS X Darwin on a x86_64 machine

#### Steps to reproduce the issue

```
#!python
from imdb import IMDb
ia = IMDb()
person = ia.search_person('Matt Damon')[0]
person_ID = person.personID
full_person = ia.get_person(person_ID)
film_dict = [x for x in full_person['filmography'] if 'actor' in x.keys() or 'actress' in x.keys()][0]
films = film_dict[list(film_dict.keys() )[0]]
film=films[8]
print film.keys()
```

#### What's the expected result?

``` 
#!python
[u'kind',
 u'title',
 u'year',
 u'canonical title',
 u'long imdb title',
 u'long imdb canonical title',
 u'smart canonical title',
 u'smart long imdb canonical title',
 u'votes'] # extra votes keyword here
```

#### What's the actual result?

``` 
#!python
[u'kind',
 u'title',
 u'year',
 u'canonical title',
 u'long imdb title',
 u'long imdb canonical title',
 u'smart canonical title',
 u'smart long imdb canonical title'] 
```

Austin

**Comment by alberanid** [comment]
closing this issue, for now.
