### ISSUE TITLE
Movie object may contain missing keys

### ISSUE THREAD

**Issue by alberanid** [alberanid/imdbpy#188]
#### Issue description

As found by @tlc in #103, Movie object may contain keys that do not exist.

#### Steps to reproduce the issue

```
import imdb

def myfunc(**kwargs):
      pass

objIA = imdb.IMDb()
movie = objIA.search_movie('Pitch Perfect 3')[0]
objIA.update(movie)
myfunc(**movie)
```

#### What's the expected result?

No KeyError exception.

#### What's the actual result?

> Traceback (most recent call last):
>   File "bug.py", line 9, in <module>
>     myfunc(**movie)
>   File "/home/tlc/.local/lib/python3.5/site-packages/imdb/utils.py", line 1495, in __getitem__
>     rawData = self.data[key]
> KeyError: 'sound crew'

**Comment by alberanid** [comment]
unable to reproduce using your code: it's always better to point to a specific movie, because search results may vary.

Anyway, looking for it I've spotted a problem with tv series episodes in search results.  It may have been related or not.

If you are able to reproduce it again with the latest version from the repository, feel free to reopen this issue.


Thanks!

**Comment by tlc** [comment]
@alberanid not sure what you mean by the first part.  That is a complete example with a specific movie in your "Steps to reproduce the issue" above.  It throws a key error for me with IMDbPY (6.6).

But I will test your changes tonight.

**Comment by alberanid** [comment]
@tlc the "specific movie" is just "the first result that you get searching for a title".
From my IP address (and country) the first result can be a different title.

If you want to print the movie ID, you can do this: `print(movie.movieID)`

Thanks for your help!

**Comment by tlc** [comment]
4765284
