### ISSUE TITLE
HTTP Connections Redirect to HTTPS - Default should be HTTPS

### ISSUE THREAD

**Issue by jh888** [alberanid/imdbpy#189]
#### Issue description

imdbpy is configured to use a base URL of 'http://www.imdb.com/', which uses the HTTP protocol to connect to imdb.com.  At some point IMDB has implemented redirects for all HTTP connections to be redirected to HTTPS.  Now every connection to http://www.imdb.com/ from imdbpy is redirected to https://www.imdb.com/ by an HTTP 301 message, which still works fine under the covers but is inefficient.  I found this behavior through packet captures, but you can also see it with any web browser by going to http://www.imdb.com addresses and seeing the address change to https.

Here is an example packet capture showing the behavior.  First a connection is made over HTTP, which receives an 'HTTP 301 Moved Permanently' redirect.  Then another connection is made over HTTPS to try to complete the query again at the new location.

![imdbpy-http-https-capture](https://user-images.githubusercontent.com/11563715/48587676-1406da80-e902-11e8-81bd-c3f2d67e1e58.jpg)

#### Version of IMDbPY, Python and OS

Python: 3.7.1
IMDbPY: 6.6
OS: uname_result(system='Windows', node='DESKTOP-57BDJ1A', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')

#### Steps to reproduce the issue

Any usage of imdbpy with the default HTTP configuration will result in HTTP 301 redirects and subsequent HTTPS connections.  It's invisible to users, but is inefficient.

#### What's the expected result?

Direct HTTPS connections.  Since all HTTP connections are redirected to HTTPS anyway, there wouldn't likely be impacts to changing it.

#### What's the actual result?

HTTP connections get redirected to HTTPS.

#### Additional details

I tested this set of changes, which resulted in direct connections for me.  Not sure if other changes may also be needed.

```
# URLs of the main pages for movies, persons, characters and queries.
#imdbURL_base = 'http://www.imdb.com/'
imdbURL_base = 'https://www.imdb.com/'

#       if not imdbURL_base.startswith('http://'):
#           imdbURL_base = 'http://%s' % imdbURL_base
        if not imdbURL_base.startswith('https://'):
            imdbURL_base = 'https://%s' % imdbURL_base
```

**Comment by alberanid** [comment]
hi @jh888 thanks for the detailed report!

In fact I was pretty sure to have already switched to https months ago, but seems that it was only in my head. :-D

I've introduced your changes in the repository version, thanks!
