### ISSUE TITLE
 s32imdbpy.py very slow

### ISSUE THREAD

**Issue by guillaumedsde** [alberanid/imdbpy#191]
#### Issue description

It is written here: https://github.com/alberanid/imdbpy/blob/master/docs/usage/s3.rst
that  s32imdbpy.py ingestion on imdb dataset files should take around an hour on a modern system.

I have a 4 core VM with 16GB of RAM and both are not very utilized during the script's runtime, its been running for about 176 minutes 51 seconds and it shows progress:
```bash
INFO:root:begin processing file /ingest/imdb_data/title.akas.tsv.gz
INFO:root:end processing file /ingest/imdb_data/title.akas.tsv.gz: 3689443 entries
INFO:root:begin processing file /ingest/imdb_data/name.basics.tsv.gz
INFO:root:end processing file /ingest/imdb_data/name.basics.tsv.gz: 8969885 entries
INFO:root:begin processing file /ingest/imdb_data/title.principals.tsv.gz
```

I was wondering whether it is normal that CPU/RAM are underutilised and that it is taking this long?

#### Version of IMDbPY, Python and OS

- **Python:** 3.7.1
- **IMDbPY:** 6.6
- **OS:** Docker official Python 3.7.1-alpine3.8
- DB Postgres 11.1 Docker https://github.com/docker-library/postgres/blob/d61fd19b699b2c380da08c3a95f7272137a182bb/11/Dockerfile

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python
python ./s32imdbpy.py ${imdb_location} postgres://${user}:${pass}@${postgre_container_ip}:${port}/imdb
```

#### What's the expected result?

- Fast IMDB data ingest, around an hour

#### What's the actual result?

- 176 minutes 51 seconds still going

#### Additional details

-

**Comment by guillaumedsde** [comment]
OK, further investigation (eg: creating DB in a ramdisk) has suggested that the problem was my VM's Disk IO speeds, sorry for the wrongly submitted issue.

**Comment by alberanid** [comment]
@guillaumedsde thanks for the notice; good to know it works.
