### ISSUE TITLE
new format of title.principals.tsv.gz file

### ISSUE THREAD

**Issue by danila99** [alberanid/imdbpy#194]
#### Issue description

1. All files from https://datasets.imdbws.com are used as the input
1. s32imdbpy.py populates SQLite DB file with no exceptions on said input
1. Using search functions return no results, when querying populated DB:

```
>>> imdb.ia.search_movie("Matrix")
2018-11-30 19:55:36,290 DEBUG | title variations: 1:[Matrix] 2:[Matrix] 3:[]
[]

```
#### Additional details
Looking at the SQLite DB I can see that:

```
select count(*) from title_akas --returns 3691577
select count(*) from title_basics --returns 5428255
select count(*) from title_crew --returns 5430167
select count(*) from title_principals --returns 30964192
```

**Comment by guillaumedsde** [comment]
I have the same problem with postresql ingest:
```
INFO:root:begin processing file /ingest/imdb_data/title.ratings.tsv.gz
INFO:root:end processing file /ingest/imdb_data/title.ratings.tsv.gz: 895649 entries
INFO:root:begin processing file /ingest/imdb_data/title.principals.tsv.gz
INFO:root:end processing file /ingest/imdb_data/title.principals.tsv.gz: 31120994 entries
INFO:root:begin processing file /ingest/imdb_data/title.episode.tsv.gz
INFO:root:end processing file /ingest/imdb_data/title.episode.tsv.gz: 3723686 entries
INFO:root:begin processing file /ingest/imdb_data/title.crew.tsv.gz
INFO:root:end processing file /ingest/imdb_data/title.crew.tsv.gz: 5449358 entries
INFO:root:begin processing file /ingest/imdb_data/title.basics.tsv.gz
INFO:root:end processing file /ingest/imdb_data/title.basics.tsv.gz: 5449358 entries
INFO:root:begin processing file /ingest/imdb_data/title.akas.tsv.gz
INFO:root:end processing file /ingest/imdb_data/title.akas.tsv.gz: 3694978 entries
INFO:root:begin processing file /ingest/imdb_data/name.basics.tsv.gz
INFO:root:end processing file /ingest/imdb_data/name.basics.tsv.gz: 8992608 entries
```

the ingest seems to happen ok, but upon actually querying the DB with `python 3.7.1` and `imdpy 6.6` using postresql on docker, I only get the name and title of a movie, no actors list, no movie cover url etc...

**Comment by alberanid** [comment]
@danila99 thanks for the report; I can confirm that the schema of the title.principals.tsv.gz file has changed.  A lot. :(

I need some time to figure how to handle it.

@guillaumedsde : thanks for the report; same problem, but in your case you also have to consider that the results of a query contains just the bare minimum of information as returned by the search query.
To fetch all the information you have to use the update method.

See https://imdbpy.readthedocs.io/en/latest/usage/query.html

**Comment by danila99** [comment]
> @danila99 thanks for the report; I can confirm that the schema of the title.principals.tsv.gz file has changed. A lot. :(

@alberanid Great stuff, at least you can see the root cause.

On the related note, if you are going to touch the upload script could you also please add some "xx% done" output to it? It takes a lot of time to run, and sometimes I am not sure whether it is still running or hanging. Even printing a simple dot every 1000 records or so would help.

**Comment by alberanid** [comment]
@danila99 , @guillaumedsde this should be fixed in the repository version.  Thanks for the bug report!

@danila99 : showing the progress makes a lot of sense, I've opened #195 and I hope to work on it soon.
