### ISSUE TITLE
show progress importing the new dataset

### ISSUE THREAD

**Issue by alberanid** [alberanid/imdbpy#195]
Show the progress made importing the new dataset.

**Comment by alberanid** [comment]
the progress is show when the **--verbose** option is used.

**Comment by ebadal** [comment]
Where should we use this option?    
--verbose

**Comment by alberanid** [comment]
@ebadal : you can add it to the other options of the **s32imdbpy.py** command, described here: https://imdbpy.readthedocs.io/en/latest/usage/s3.html
