### ISSUE TITLE
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode

### ISSUE THREAD

**Issue by h3llrais3r** [alberanid/imdbpy#201]
#### Issue description
Encoding issue when searching for unicode string with special characters.

#### Version of IMDbPY, Python and OS
Running Python 2.7.15 on Windows

#### Steps to reproduce the issue
Execute search movie on Python 2 with unicoded string.

```
#!python

IMDb().search_movie(u'Kyatapirâ')

```
#### What's the expected result?
Movie details are fetched

#### What's the actual result?

```
File "C:\Tools\GitHub\Auto-Subliminal\lib\imdb\__init__.py", line 422, in search_movie
    res = self._search_movie(title, results)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\imdb\parser\http\__init__.py", line 435, in _search_movie
    cont = self._get_search_content('tt', title, results)
  File "C:\Tools\GitHub\Auto-Subliminal\lib\imdb\parser\http\__init__.py", line 420, in _get_search_content
    params = 'q=%s&s=%s' % (quote_plus(ton, safe=''), kind)
  File "c:\tools\python27\Lib\urllib.py", line 1305, in quote_plus
    return quote(s, safe)
  File "c:\tools\python27\Lib\urllib.py", line 1298, in quote
    return ''.join(map(quoter, s))
KeyError: u'\xe2'

c:\tools\python27\Lib\urllib.py:1298: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
    return ''.join(map(quoter, s))
```

#### Additional details

![image](https://user-images.githubusercontent.com/1945295/51402876-031b5500-1b4f-11e9-999c-12cc4e8be52d.png)

![image](https://user-images.githubusercontent.com/1945295/51402897-0dd5ea00-1b4f-11e9-96a0-566aacc06545.png)

Encoding the unicode string before passing it to `search_movie` doesn't work either because the import above converts the `safe` value to unicode, which causes a unicode error.

I think it might be related to the fact that the map in urllib is not in unciode.
When I remove the `from __future__ import unicode_literals` in `imdb\parser\http\__init__.py` and convert my unicode string to a native string (str in Python 2) the code works.

If you don't want to remove the `unicode_literals` import, I propose that for `PY2`, you always encode unicode strings. I tried it out and this works:
![image](https://user-images.githubusercontent.com/1945295/51403702-876ed780-1b51-11e9-9b5c-81d7b440d69c.png)

However, this is only needed for `PY2` because existing code works with `PY3`.

**Comment by alberanid** [comment]
Hi @h3llrais3r ; pardon for the long delay.

I've applied the proposed patch to the version in the repository and added your nickname to the credits. Thanks!

**Comment by h3llrais3r** [comment]
@alberanid No problem, thanks for applying the patch. :wink:
