### ISSUE TITLE
SAVING imdbID values for movies... SKIPPING: unable to retrieve data: relation "title" does not exist

### ISSUE THREAD

**Issue by ebadal** [alberanid/imdbpy#204]
I am getting following issue when I ran the file on the dataset provided in https://www.imdb.com/interfaces/

RUNNING imdbpy2sql.py
SAVING imdbID values for movies... SKIPPING: unable to retrieve data: relation "title" does not exist
LINE 1: SELECT md5sum, imdb_id FROM title WHERE imdb_id IS NOT NULL
                                    ^

SAVING imdbID values for people... SKIPPING: unable to retrieve data: current transaction is aborted, commands ignored until end of transaction block

SAVING imdbID values for characters... SKIPPING: unable to retrieve data: current transaction is aborted, commands ignored until end of transaction block

SAVING imdbID values for companies... SKIPPING: unable to retrieve data: current transaction is aborted, commands ignored until end of transaction block

**Comment by alberanid** [comment]
pardon the long delay; those are just warnings that can be ignored safely. Did the command complete successfully?

**Comment by alberanid** [comment]
closing this issue, for now
