### ISSUE TITLE
SyntaxError: invalid syntax   when running python imdbpy2sql.py

### ISSUE THREAD

**Issue by RickJP** [alberanid/imdbpy#206]
#### Issue description

IMDbPY-6.6   |   Python 3.6.7  |  Ubuntu 18.04
I run this on Ubuntu 18 and all dependencies for Python are installed, as far as I am aware . The data is in the .tsv format in the data folder.

I run =>
python imdbpy2sql.py -d /home/dragon/IMDB/imdb_data -u 'mysql://rick:<PASSWORD>@localhost/imdb' --mysql-force-myisam

...and receive ONLY this error message.
   File "imdbpy2sql.py", line 1104
    print('WARNING %s._toDB() invalid title:' % self.className, end=' ')****

**Comment by alberanid** [comment]
@RickJP : are you sure that python is the interpreter for python3?  On Ubuntu it's usually linked to Python 2.  Try calling it with **python3**

**Comment by RickJP** [comment]
Thanks. That sorted it.
