### ISSUE TITLE
How to scrap for indian top 250 rated movies 

### ISSUE THREAD

**Issue by yashwanth2804** [alberanid/imdbpy#207]
How can I customly provide url for `get_top250_movies` .
Is it possible for provide at runtime arguments

**Comment by alberanid** [comment]
hi @yashwanth2804 : at the moment, the url is hardcoded.

However, you can modify line 297 of __init__.py to something like this:
`imdbURL_top250 = imdbURL_base + 'india/top-rated-indian-movies'`

A pull request to make it possible to customize every URL is welcome, obviously.

**Comment by alberanid** [comment]
closing this issue, for now

**Comment by alberanid** [comment]
This issue was implemented in #260
