### ISSUE TITLE
Episode Ratings Not Showing

### ISSUE THREAD

**Issue by CGraabaek** [alberanid/imdbpy#210]
#### Issue description

'episodes rating' is no longer pulling in ratings for individual episodes.

#### Version of IMDbPY, Python and OS

- **Python:** `3.7.1`
- **IMDbPY:** `6.6` 
- **OS:** `MacOS`

#### Steps to reproduce the issue

Pull in a TV Show and update both 'episodes' and 'episodes rating' - data is not parsed for episodes rating

```  #!p-ython   
        import imdb
        i = imdb.IMDb()
        imdb_data = i.get_movie("5770786")
        i.update(imdb_data, 'episodes')
        i.update(imdb_data, 'episodes rating')
        print(imdb_data['episodes'])
        print(imdb_data['episodes rating'])
# your code here
```

Alternate version tried: 

```
from imdb import IMDb
ia = IMDb()

series = ia.get_movie('5770786')
ia.update(series, 'episodes')
for season_nr in sorted(series['episodes']):
    for episode_nr in sorted(series['episodes'][season_nr]):
        episode = series['episodes'][season_nr][episode_nr]
        print('episode #%s.%s; rating: %s; votes: %s' %
              (season_nr, episode_nr, episode.get('rating'), episode.get('votes')))
```
#### What's the expected result?

- Episodes rating should print out data

#### What's the actual result?

- There is no data

#### Additional details

- Individual episodes do have 'rating' info when accessed directly using get_movie('6016432'), but this is a _slow_ process.

**Comment by udubnate** [comment]
thanks I am also having the same issue, neither episodes or episodes rating infoset is pulling the information

**Comment by alberanid** [comment]
should be fixed in the repository version. Thanks for the report!
