### ISSUE TITLE
Is the imdbID still an issue in local database?

### ISSUE THREAD

**Issue by internalG** [alberanid/imdbpy#226]
#### Issue description
FAQ section in doc talks a lot of imdbID, but in the new tsv file, the tconst or titleId column is just the imdbID on web site. Is there anything special to use that?

**Comment by alberanid** [comment]
Hi @internalG , there's nothing special to do.

For example:

```
from imdb import IMDb
ia = IMDb('s3', uri='sqlite:////home/da/imdbs3.sql')
kr = ia.search_person('Keanu Reeves')[0]
print(kr.personID)
```

Will print '206'. Please notice that on the web the IDs are strings of seven digits, so if you have to pad it with zeroes; e.g.: print('%07d' % kr.personID)

**Comment by internalG** [comment]
Thanks. The doc is outdated.
