### ISSUE TITLE
error documentation page source code adult search

### ISSUE THREAD

**Issue by catafest** [alberanid/imdbpy#227]
#### Issue description
documentation example https://imdbpy.readthedocs.io/en/latest/usage/adult.html
*write the description here*
>>> ia = IMDb(accessSystem='http')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'IMDb' is not defined

#### Version of IMDbPY, Python and OS
C:\Python373>python.exe -V
Python 3.7.3
C:\Python373>python.exe  -c "import imdb ; print(imdb.VERSION)"
6.8
C:\Python373>python -c "import platform ; print(platform.uname())"
uname_result(system='Windows', node='My_CGF_PC', release='8.1', version='6.3.960
0', machine='AMD64', processor='Intel64 Family 6 Model 58 Stepping 9, GenuineInt
el')

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
- **IMDbPY:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`
- **OS:** `python -c 'import platform ; print(platform.uname())'`

#### Steps to reproduce the issue
open the python 3.7.3 and use the example:
>>> import imdb
>>> ia = imdb.IMDb()
>>> ia = IMDb(accessSystem='http')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'IMDb' is not defined
*if possible, provide a minimal code to reproduce the problem*

```
#!python

# your code here
```

#### What's the expected result?

- 

#### What's the actual result?

- 

#### Additional details

-

**Comment by alberanid** [comment]
thanks, I updated the documentation
