### ISSUE TITLE
Goofs parser is broken

### ISSUE THREAD

**Issue by kattstof** [alberanid/imdbpy#228]
when doing the example code 
ia.update(the_unt, 'goofs')
print(the_unt['goofs'][0])`
i get a Key Error
i've tried just copy pasting the examples in the console window everything works except grabbing goofs

**Comment by alberanid** [comment]
yes, the goofs parser was broken. Should be fixed in the repository version, now.

The 'goofs' keys will return a list of objects like this: `{'category': 'Audio/visual unsynchronised', 'text': 'When Neo meets Trinity...'}`
