### ISSUE TITLE
Please add a warning in the readme that exceptions cannot be caught by default.

### ISSUE THREAD

**Issue by lucidBrot** [alberanid/imdbpy#238]
#### Issue description

As per [this](https://stackoverflow.com/q/58124534/2550406) question on stackoverflow, the following simple code does not print "error":

```
#!python
import imdb
from imdb import IMDbDataAccessError
try:
    ia = imdb.IMDb(accessSystem='http')
    movie = ia.get_movie('12121212212121')
except:
    print("error")
```
I found out that there is a setting for that. The following code behaves as expected:

```
#!python
import imdb
from imdb import IMDbDataAccessError
try:
    ia = imdb.IMDb(accessSystem='http', reraiseExceptions=True)
    movie = ia.get_movie('12121212212121')
except:
    print("error")

So I assume this is intended behaviour on your part. But I think that behaviour should be documented somewhere. It's confusing at least to me and the person asking that question.
```

#### Version of IMDbPY, Python and OS

- **Python:** `python 3.6.7 :: Anaconda, Inc.`
- **IMDbPY:** `6.8`
- **OS:** `uname_result(system='Windows', node='Sharkoon', release='10', version='10.0.15063', machine='AMD64', processor='Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')`

#### Steps to reproduce the issue

See the first code sample above. Confusingly, having a [imdbpy.cfg](https://github.com/alberanid/imdbpy/blob/39fb3b8ce3d90e7b4ea803a722811ea0c6c8df8b/docs/imdbpy.cfg) in the same directory with `reraiseExceptions = on` did not modify the behaviour.

#### What's the expected result?

The program should print "error"

#### What's the actual result?

The program finishes without printing "error", but shows the stack trace

**Comment by alberanid** [comment]
I think it would be better to just always raise the exception.

I'll consider the change for a future release.

**Comment by aptlin** [comment]
Any updates?

**Comment by alberanid** [comment]
Just committed a change to the default behavior: now if not specified **reraiseExceptions** is True.

This means that any exception is re-raised.

If this breaks something important let us know, but I think this should be better handled catching the exception in the caller code.
