### ISSUE TITLE
Support for persons with several IDs and redirect from one to another

### ISSUE THREAD

**Issue by ramusus** [alberanid/imdbpy#242]
#### Issue description

I just found iMDB has in some rare cases persons with several IDs, which were merged into one. If you try to load https://www.imdb.com/name/nm1890852/, you will be redirected to 
https://www.imdb.com/name/nm0440022/. I think this means, first person was merged with the last one. Is this library support such cases? I need to get new ID when trying to update info by old ID.

#### Version of IMDbPY, Python and OS

- **Python:** 3.0
- **IMDbPY:** 6.7dev20180815
- **OS:** MacOSX

**Comment by alberanid** [comment]
from a quick test, the data is collected in both cases, but it keep the imdbID given doing the query.
I think it's possible to also extract the imdbID from the web page, but I'm not so sure we can always do it safely (I have to think about it and do some tests)

**Comment by alberanid** [comment]
for the moment, I've introduced the "imdbID" key in the Movie and Person objects.

The movie.imdbID will still contain the requested ID, but movie.get("imdbID") will show you the real one, after the redirect.
