### ISSUE TITLE
Person filmography is not working as documented

### ISSUE THREAD

**Issue by Dobatymo** [alberanid/imdbpy#244]
#### Issue description

Using `julia = i.get_person('0000210')` from the docs, it should be possible to use `julia['actress']`. However this key does not exist. One can use the `julia['filmography']`, but this object is malformed also. It's a list of dictionaries, each with one key only, instead of just one dictionary with multiple keys.
```
>>> julia['filmography'][0].keys()
dict_keys(['actress'])
>>> julia['filmography'][1].keys()
dict_keys(['producer'])
```

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.7.4
- **IMDbPY:** 6.8
- **OS:** uname_result(system='Windows', node='xxx', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 78 Stepping 3, GenuineIntel')

#### Steps to reproduce the issue

```
#!python
from imdb import IMDb
i = IMDb()
julia = i.get_person('0000210')
julia['actress']
```

#### What's the expected result?

- No KeyError

#### What's the actual result?

- A KeyError...

**Comment by alberanid** [comment]
thanks for the bug report!

I've fixed the parser; you can now do something like this:
```
from imdb import IMDb
i = IMDb()
julia = i.get_person('0000210')
for job in julia['filmography'].keys():
    print('# JOB: ', job)
    for movie in julia['filmography'][job]:
        print('\t%s %s (role: %s)' % (movie.movieID, movie['title'], movie.currentRole))
```
