### ISSUE TITLE
update episodes - missing pilot

### ISSUE THREAD

**Issue by Ryandev** [alberanid/imdbpy#25]
If you run the following commands:
    `import imdb`
    `i = imdb.IMDb()`
    `res = i.search_movie('blackadder')`
    `r1 = res[0]`
    `i.update(r1,'episodes')`
    `print str(r1['episodes'])`

You will get the following results:
`{1: {1: <Movie id:0526541[http] title:_"The Black Adder" The Foretelling (1983)_>, 2: <Movie id:0526537[http] title:_"The Black Adder" Born to Be King (1983)_>, 3: <Movie id:0526539[http] title:_"The Black Adder" The Archbishop (1983)_>, 4: <Movie id:0526542[http] title:_"The Black Adder" The Queen of Spain's Beard (1983)_>, 5: <Movie id:0526543[http] title:_"The Black Adder" Witchsmeller Pursuivant (1983)_>, 6: <Movie id:0526540[http] title:_"The Black Adder" The Black Seal (1983)_>}}`

which is missing the pilot episode ref: (http://www.imdb.com/title/tt0084988/episodes?season=1&ref_=tt_eps_sn_1)

Tested on latest version (cc63c251300eb322262795cbf17d434669566097)

**Comment by alberanid** [comment]
Thanks for the notice: it should be fixed, now. :-)
