### ISSUE TITLE
Strange numbers for box office

### ISSUE THREAD

**Issue by bessarabov** [alberanid/imdbpy#253]
## example 1

I'm trying to get box office info for the movie Diamonds Are Forever (1971) https://www.imdb.com/title/tt0066995/ Here is the code:

```
from imdb import IMDb

ia = IMDb()

movie = ia.get_movie('0066995')

print(movie['box office'])
```

the output is:

```
{'Budget': '$7,200,000 (estimated)', 'Cumulative Worldwide Gross': '$116,000,000'}
```

And here is the screenshot from the page https://www.imdb.com/title/tt0066995/ 

![Screenshot 2020-02-13 at 18 46 16](https://user-images.githubusercontent.com/47263/74451743-23702d00-4e91-11ea-907d-e016e1d2d251.png)

As use can see the IMDbPY got the correct `Budget` value, but for the `Cumulative Worldwide Gross` the numbers from the lib and from the site differ.

## example 2

On Her Majesty's Secret Service (1969) — https://www.imdb.com/title/tt0064757/

```
from imdb import IMDb

ia = IMDb()

movie = ia.get_movie('0064757')

print(movie['box office'])
```
output:
```
{'Budget': '$7,000,000 (estimated)', 'Opening Weekend United Kingdom': 'GBP16,460, 24 Dec 1969'}
```
![Screenshot 2020-02-13 at 18 49 50](https://user-images.githubusercontent.com/47263/74452085-a2fdfc00-4e91-11ea-989a-96c90889bc51.png)

The Budget is correct, but there is field `Cumulative Worldwide Gross` in the library output

#### Version of IMDbPY, Python and OS

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
```
3.7.2 (default, Mar 27 2019, 08:41:08) 
[GCC 6.3.0 20170516]
```

- **IMDbPY:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`

```
6.8
```

- **OS:** `python -c 'import platform ; print(platform.uname())'`
```
uname_result(system='Linux', node='1846688d02cc', release='4.19.76-linuxkit', version='#1 SMP Thu Oct 17 19:31:58 UTC 2019', machine='x86_64', processor='')
```

#### Steps to reproduce the issue

see the first section

#### What's the expected result?

see the first section

#### What's the actual result?

see the first section

#### Additional details

-

**Comment by alberanid** [comment]
Hi @bessarabov , thanks for the report.

Apparently, the presented information depends on various factors like the IP of the request, the operating system settings and the browser supported languages.

I confirm that what you get in the browser is something like what you get, but doing the same query from the IMDb library will show some different information.

As an example, for the "0064757" title we have:
```
            <section class="titlereference-section-box-office">
                <h4 class="ipl-header__content ipl-list-title">Box Office</h4>
                <table class="titlereference-list ipl-zebra-list">
        <tr class="ipl-zebra-list__item">
            <td class="ipl-zebra-list__label">Budget</td>
            <td>
                    $7,000,000 (estimated)
            </td>
        </tr>
        <tr class="ipl-zebra-list__item">
            <td class="ipl-zebra-list__label">Opening Weekend United Kingdom</td>
            <td>
                    GBP16,460, 24 Dec 1969
            </td>
        </tr>
                </table>
            </section>
```

I think there is not much we can do about it.

For the moment I'll close this issue.  If you have any idea for improvements, feel free to open another one.

Thanks!
