### ISSUE TITLE
AttributeError: module 'imdb' has no attribute 'IMDb'

### ISSUE THREAD

**Issue by senorsi** [alberanid/imdbpy#258]
#### Issue description

When I call a python script with import imdb or from imdb import IMDb, IMDbError I get the error: 

AttributeError: module 'imdb' has no attribute 'IMDb'

It works just fine when I open Python and type the commands in there.

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.7.7
- **IMDbPY:** 6.8
- **OS:** Windows 10 (64)

#### Steps to reproduce the issue

import imdb

#### What's the expected result?

- Importing the module successfully.

#### What's the actual result?

- Aforementioned error message

#### Additional details

-

**Comment by alberanid** [comment]
Apparently there's a problem on your installation of IMDbPY.

How did you do to install it?

Best option: `pip3 install git+https://github.com/alberanid/imdbpy` (you need to install pip3; I don't know how to do it in Windows)

**Comment by senorsi** [comment]
OK, installing it with git+https://github.com/alberanid/imdbpy fixed the issue. Thanks.
