### ISSUE TITLE
Cannot get cover url

### ISSUE THREAD

**Issue by GrbavaCigla** [alberanid/imdbpy#263]
#### Issue description
Cannot get cover url

#### Version of IMDbPY, Python and OS

- **Python:** 3.8.2
- **IMDbPY:** 6.9dev20200503
- **OS:** GNU/Linux

#### Steps to reproduce the issue

```python
import imdb
ia = imdb.IMDb()
movie = ia.get_top250_movies()[0]
print(movie['cover'])
```

#### What's the actual result?
```python
Traceback (most recent call last):
  File "issue.py", line 7, in <module>
    print(movie['cover'])
  File "/usr/lib/python3.8/site-packages/imdb/utils.py", line 1503, in __getitem__
    rawData = self.data[key]
KeyError: 'cover url'
```

**Comment by filipbacic** [comment]
You just need to put 
ia.update(movie) 
before the print statement.

**Comment by alberanid** [comment]
@filipbacic answer is correct: many parsers (e.g. search_movie) will return just basic information about a movie, that can be updated using the ia.update(movie) call.

However, in this specific case, it would also be possible to improve the DOMHTMLTop250Parser to also parse the cover url, since it should be available in the HTML.

**Comment by GrbavaCigla** [comment]
Thanks! That worked.

**Comment by GrbavaCigla** [comment]
Also is it possible to change size of image (I don't want to download full-size)? If not, I saw `cover url` is just full-size image with parametars.

**Comment by alberanid** [comment]
@GrbavaCigla the URL of the full-size version should be available in the `"full-size cover url"` key of the Movie object (`"full-size headshot"` for Person instances).

I'm not sure if it's possible to generate the URLs for other sizes.

**Comment by GrbavaCigla** [comment]
It is, here is the evidence:
Joker `cover url`: https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY150_CR0,0,101,150_.jpg
Joker `full-size cover url`: https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@.jpg
Joker custom sized to 659x979: https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY1000_CR0,0,674,1000_AL_.jpg

**Comment by GrbavaCigla** [comment]
after `@_V1_` you can add you can change size with `SY[size]` where `_` is delimiter for arguments.
Also `CR0,0,101,150` is for cropping and isn't necessery.
