### ISSUE TITLE
Add Image Manipulation

### ISSUE THREAD

**Issue by GrbavaCigla** [alberanid/imdbpy#265]
### Description
It would be really nice to add image manipulation because imdb supports it.
### Formatting arguments
Between `@` and `.jpg` you can add arguments separated by `_`
### Image Arguments
`V1` - Version 1 I quess
`SY` - size on Y
`SX` - size on X
`CR` - Crop, arguments of crop separated by `,`
`AL` - Always on the end, don't know what it does

[Example](https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_CR0,4,100,200_AL_.jpg)
![alt example result](https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SY1000_CR0,4,100,200_AL_.jpg)

**Comment by alberanid** [comment]
Yes, that's a good idea.

Probably the best place to put it, is a simple function in the imdb.helpers module.

We could also see if the same rules apply to people's headshots.

**Comment by GrbavaCigla** [comment]
I checked now, crop works for headshots, but not sure for `SY` and `SX`

**Comment by alberanid** [comment]
Fixed in #269
