### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by MaxNoe** [alberanid/imdbpy#27]
As Guido von Rossum said this PyCon, everybody should start switiching to python3.

**Comment by alberanid** [comment]
Eh... it would be nice: unfortunately right now IMDbPY suffers from bigger problems.

I don't have much spare time for it, and I receive very few contribution from the community.
As always, if anyone is willing to help, I'll be glad to explain what's needed. :-)

**Comment by bashu** [comment]
+1 I can maintain it, add me as contributor

**Comment by alberanid** [comment]
Does anyone already have a working set of changes?

Plus, will the changes maintain compatibility with Python 2.x?  If this can't be done, I guess it's better to keep them as separated projects (otherwise, I'd be happy to merge changes to make it compatible with 3.x, obviously :-))

Thanks for the help!

**Comment by MaxNoe** [comment]
Most of the things can be done by using the `six` module which provides a compatibility layer for python2 and 3 for a script to work on both python2 and 3.

For example `raw_input` vs `input` is solved by:

```
from six.moves import input

answer = input()
```
If python is version2 `six.moves.input` is `raw_input`, for python3 it is `input`.

**Comment by MaxNoe** [comment]
Oh and obviously the `__future__` imports (at least `print_function, absolute_import`)

**Comment by MaxNoe** [comment]
* `except Error, e` has to be `except Error as e`

```
from __future__ import print_function
import sys

print('Hello World', file=sys.stderr)
```

**Comment by staticdev** [comment]
Any plans for this?

**Comment by alberanid** [comment]
@staticdev : generally speaking, we have more cravings than plans. :-)

There are some ongoing efforts, but I'm not sure how advanced they are.  I'd obviously love to add support for Python 3, and a parser for the new format of the plain text data files, but I have next to no time for this. :'(

**Comment by alberanid** [comment]
The current effort is taking place in the 'codename-simplify' branch.

Right now we're switching to native Python 3 (no six module)

**Comment by alberanid** [comment]
Python 3 version merged into master.  The old Python 2.7 version is in the branch "imdbpy-legacy".
