### ISSUE TITLE
Broken manual installation

### ISSUE THREAD

**Issue by renatosamperio** [alberanid/imdbpy#281]
#### Issue description

*Can't install library manually to latest in master*

#### Version of IMDbPY, Python and OS

- **Python:** `python -V`: Python 2.7.12

- **IMDbPY:**  `python -c 'import imdb ; print(imdb.VERSION)'`: 2020.07.29
- **OS:** `python -c 'import platform ; print(platform.uname())'`:('Linux', 'xxx', '4.15.0-112-generic', '#113~16.04.1-Ubuntu SMP Fri Jul 10 04:37:08 UTC 2020', 'x86_64', 'x86_64')

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
python setup.py build
sudo python setup.py install
```

#### What's the expected result?

- To be installed in my system

#### What's the actual result?

- Error output:

```
...
Extracting IMDbPY-2020.7.29-py2.7.egg to /usr/local/lib/python2.7/dist-packages
  File "/usr/local/lib/python2.7/dist-packages/IMDbPY-2020.7.29-py2.7.egg/imdb/helpers.py", line 613
    resultImage += f'SX{width}_'
                               ^
SyntaxError: invalid syntax


```

#### Additional details

- Fixed removing f-string items:
```
diff --git a/imdb/helpers.py b/imdb/helpers.py
index 5d752d8..b07f329 100644
--- a/imdb/helpers.py
+++ b/imdb/helpers.py
@@ -610,13 +610,13 @@ def resizeImage(image, width=None, height=None, crop=None):
     resultImage += '@._V1_'
 
     if width:
-        resultImage += f'SX{width}_'
+        resultImage += 'SX{width}_'
     if height:
-        resultImage += f'SY{height}_'
+        resultImage += 'SY{height}_'
 
     if crop:
         cropVals = ','.join(crop)
-        resultImage += f'CR{cropVals}_'
+        resultImage += 'CR{cropVals}_'
 
     resultImage += '.jpg'
 
```

**Comment by alberanid** [comment]
should be fixed in the latest version (2020.8.12)

thanks for the bug report!
