### ISSUE TITLE
module 'imdb.parser.sql.logging' has no attribute 'getLogger'

### ISSUE THREAD

**Issue by valco1994** [alberanid/imdbpy#287]
#### Issue description

I'm trying to use `imdbpy2sql.py` now. I have checked different versions of `imdbpy`, and when I succeded with `build` and `install` steps, I got a crash with the following exception: 
```
Traceback (most recent call last):
  File "/home/valco1994/.local/bin/imdbpy2sql.py", line 42, in <module>
    from imdb.parser.sql.dbschema import DB_SCHEMA, dropTables, createTables, createIndexes
  File "/home/valco1994/.local/lib/python3.8/site-packages/imdb/parser/sql/__init__.py", line 555, in <module>
    class IMDbSqlAccessSystem(IMDbBase):
  File "/home/valco1994/.local/lib/python3.8/site-packages/imdb/parser/sql/__init__.py", line 560, in IMDbSqlAccessSystem
    _sql_logger = logging.getLogger('imdbpy.parser.sql')
AttributeError: module 'imdb.parser.sql.logging' has no attribute 'getLogger'
```
#### Version of IMDbPY, Python and OS

I have checked it with the current `master` branch and with different tags of this repository.
I use `Python 3.8.2`, `IMDbPy 2020.09.25` running on Ubuntu 20.04.1 LTS on x86_64 architecture and Linux kernel `5.4.0-47-generic`.

#### Steps to reproduce the issue

It's enough to try to start `imdbpy2sql.py` from a terminal, even without any parameters to reproduce this error.

**Comment by alberanid** [comment]
thanks for the report!

It should be fixed in the repository, now.

**Comment by valco1994** [comment]
Thank you!
