### ISSUE TITLE
Translation question

### ISSUE THREAD

**Issue by GrbavaCigla** [alberanid/imdbpy#288]
Hi, me again. I would like to make translation to serbian language because I need it for my project. Would you merge my pr if I translate it? Thanks.

**Comment by alberanid** [comment]
Hi @GrbavaCigla,
sure, I'd be glad to add a new language.

You can just create a `.po` file from the `.pot` in **imdb/locale** or - if you prefer - you can use our Transifex project to manage translations.  I've just added Serbian: https://www.transifex.com/davide_alberani/imdbpy/language/sr/ (you can edit directly on the web and generate the .po from there).

If you have any question, feel free to ask.

Thanks.

**Comment by GrbavaCigla** [comment]
#289

**Comment by alberanid** [comment]
merged: closing this issue
