### ISSUE TITLE
What's the legality of using IMDbPy?

### ISSUE THREAD

**Issue by agenttux** [alberanid/imdbpy#295]
I want to use data from IMDbPy for a personal FOSS website but I'm not sure that using it is legal according to IMDb's [TOS](https://m.imdb.com/conditions). Does using IMDbPy violate the `Robots and Screen Scraping` clause?

> **Robots and Screen Scraping:** You may not use data mining, robots, screen scraping, or similar data gathering and extraction tools on this site, except with our express written consent as noted below. 

If I go ahead and download the [s3 datasets](https://www.imdb.com/interfaces/) and use that data with IMDbPY, would that be allowed? If I made the site under any of these conditions, would IMDb have grounds to come after me legally? I asked IMDb about access to their full official API and the cost of using it is ridiculously expensive ($150,000 a year), so I am looking for a good and preferably legal alternative. Thanks for any information.

**Comment by alberanid** [comment]
Standard disclaimer: IANAL.

On using the s3 (or the old plain text data files) data set: you can use it as long as it's for personal and non-profit usage.

The same rules applies on the data fetched from the IMDb web pages; selling and in general redistributing the data is obviously forbidden. Obviously also building a commercial (or even free) service out it it is forbidden.

Regarding the screen scraping clause: again, IANAL. To the best of my knowledge, this kind or terms are not enforceable everywhere (maybe they are valid in the U.S., maybe not in E.U.); also, as far as I know IMDbPY is not circumventing any technical restriction (DRM) and so the most strict rules of DMCA should not apply.
Another thing to consider is that those kind of clauses are usually there to prevent mass-scraping, something that we do not support of-of-the-box and totally do not encourage.

Currently IMDbPY is mostly used by people who want to manage their own movie collection and - especially - by data scientists who use it to analyse an important, real-world, data set; we always invite everyone to respect the license terms of the data they are using.

Regarding the alternatives, you may want to look at one or more of the following, which may also have a nice API:
* https://www.omdbapi.com/
* https://www.themoviedb.org/
* https://thetvdb.com/

Hope this helps.
