### ISSUE TITLE
imdbpy out of memory when call search_movie('1984") from s3

### ISSUE THREAD

**Issue by bpolya** [alberanid/imdbpy#296]
#### Issue description

import imdb
ia = imdb.IMDb('s3', 'mysql+mysqldb://imdb@_mysql_/imdb')                                                                                                                    
results = ia.search_movie('1984")

Out of memory: Killed process 3810 (python3) total-vm:7180912kB, anon-rss:5162948kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:12176kB oom_score_adj:0

#### Version of IMDbPY, Python and OS

Python 3.8.5
6.8
system='Linux', node='ubuntu', release='5.4.0-54-generic', version='#60-Ubuntu SMP Fri Nov 6 10:37:59 UTC 2020', machine='x86_64', processor='x86_64'
SQL:  mariadb 10.3.25 (debian, myisam tables)
#### Steps to reproduce the issue
python3 s32imdbpy.py /_imdb-tsv/ mysql+mysqldb://imdb@_mysql_/imdb?charset=utf8

import imdb
ia = imdb.IMDb('s3', 'mysql+mysqldb://imdb@_mysql_/imdb')                                                                                                                    
results = ia.search_movie('1984")

#### What's the expected result?
get some result before run out from memory (6gb ram + 2gb swap)

#### What's the actual result?

Out of memory: Killed process 3810 (python3) total-vm:7180912kB, anon-rss:5162948kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:12176kB oom_score_adj:0 

#### Additional details

minimal test script for query 1984 from the database run without problem (hence i guess - the 32imdbpy import was successfull and the db connection is ok,  and the whole result metadata in python list consume less than 24mb)

#!/usr/bin/python3
import tracemalloc
tracemalloc.start()
import mysql.connector
import time
mydb = mysql.connector.connect(host="192.168.2.8", user="imdb", database="imdb")
mycursor = mydb.cursor()
begin = time.time()
query = 'select * from title_akas where title like "%1984%";'
mycursor.execute(query)
myresult = mycursor.fetchall()
movielist = list()
for x in myresult:
    movielist.append(x)
end = time.time()
print(len(myresult))
print(f"Total runtime of the program is {end - begin}")
c, p = tracemalloc.get_traced_memory()
print(f"Current memory usage is {c/ 1000000}MB; Peak was {p/ 1000000}MB")
tracemalloc.stop()

21186
Total runtime of the program is 14.008947134017944
Current memory usage is 12.03274MB; Peak was 23.426715MB

**Comment by alberanid** [comment]
I was able to reproduce it also using the SQLite backend, so it isn't a problem in the MySQL/MariaDB connector.

It's probably related to the query done using the soundex of the searched title.

I will try to work on it in the next days/weeks; thanks for the report!

**Comment by bpolya** [comment]
Thank You very much,
I will try it on next week.

On February 7, 2021 6:20:11 PM UTC, Davide Alberani <notifications@github.com> wrote:
>I was able to reproduce it also using the SQLite backend, so it isn't a problem in the MySQL/MariaDB connector.
>
>It's probably related to the query done using the soundex of the searched title.
>
>I will try to work on it in the next days/weeks; thanks for the report!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/alberanid/imdbpy/issues/296#issuecomment-774725852
-- 
Polya Balazs

**Comment by alberanid** [comment]
should be fixed in the repository version.  Basically there are too many titles in the title_akas tables with empty soundex (non-ascii titles, mainly); in that case, we try an `ILIKE "%title%"` query.

**Comment by bpolya** [comment]
Can i update with pip/pypi or need to clone with git?

**Comment by alberanid** [comment]
Not sure, but probably something like this could work: pip install git+
https://github.com/alberanid/imdbpy --upgrade

(not tested)

The imdb.VERSION should be set to today.

Il dom 7 feb 2021, 20:26 bpolya <notifications@github.com> ha scritto:
