### ISSUE TITLE
get_movie() takes lots of time ..very slow performance 

### ISSUE THREAD

**Issue by Sahil-pixel** [alberanid/imdbpy#298]
#### Issue description

*write the description here*
get_movie() takes lots of time ..TO EXECUTE

#### Version of IMDbPY, Python and OS

**NOTICE: please always try the latest version from the repository before submitting a bug.**

- **Python:** 3.6.9
- **IMDbPY:** 2020.09.25
- **OS:**  kubuntu 18.04

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python

import imdb
ia=imdb.IMDb()
m=ia.get_top250_movies()
#print(m)
for i in m:
	#print(i)
	movie = ia.get_movie(i.movieID)
	print(movie)
# your code here
```

#### What's the expected result?

- 

#### What's the actual result?

- 

#### Additional details

-

**Comment by alberanid** [comment]
that's probably normal, and also depends on the speed of your Internet connection.

You can speed up doing some parallelism, but IMDbPY is not meant to be used that way, so it doesn't provide any helpers for it.

Hope this helps.

**Comment by Sahil-pixel** [comment]
X=get_top250_movies()
print(x.items())
running fast getting enough information ..But I also need 'cover url' but x.items() not giving this.

**Comment by alberanid** [comment]
closing, since the performance issue is not a problem.

For any other improvements, any pull request is welcome.

**Comment by 1951FDG** [comment]
When you mention that parallelism may be an option, but IMDbPY is not meant to be used that way, can IMDbPY be used safely employing parallelism of some kind? I can't seem to find an example online.
