### ISSUE TITLE
Using tuple or other sequence/iterable types as `season_nums` parameter of `update_series_seasons` raises `KeyError`

### ISSUE THREAD

**Issue by x11x** [alberanid/imdbpy#300]
#### Issue description

Trying to use `IMDbHTTPAccessSystem.update_series_seasons` to retrieve only a single season of a tv series instead of all seasons does not work, raises `KeyError: 'data'`.

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.9.1
- **IMDbPY:** 2020.12.20
- **OS:** Windows 10 10.0.18362 AMD64

#### Steps to reproduce the issue

```
from imdb import IMDb
ia = IMDb()
s = ia.get_movie('0264235')
ia.update_series_seasons(s, season_nums=(10,))
```

#### What's the expected result?
`s` is updated with `s['episodes']` key populated with only season 10 episodes.

#### What's the actual result?
```
2021-01-21 14:46:08,846 CRITICAL [imdbpy] c:\users\evan\desktop\venv\lib\site-packages\imdb\__init__.py:851: caught an exception retrieving or parsing "episodes" info set for mopID "0264235" (accessSystem: http)
Traceback (most recent call last):
  File "c:\users\evan\desktop\venv\lib\site-packages\imdb\__init__.py", line 849, in update_series_seasons
    ret = method(mopID, season_nums)
  File "c:\users\evan\desktop\venv\lib\site-packages\imdb\parser\http\__init__.py", line 641, in get_movie_episodes
    data_d['data']['number of episodes'] = nr_eps
KeyError: 'data'
```

#### Additional details

Trying to use `IMDbHTTPAccessSystem.get_movie_episodes` directly (e.g. `ia.get_movie_episodes('0264235', season_nums=(10,))`) raises the same error.

I can see in [get_movie_episodes](https://github.com/alberanid/imdbpy/blob/58e9781afedcefe37865b614babb271fb55d8a70/imdb/parser/http/__init__.py#L611) that `data_d['data']` is never initialized but I can't figure out how its supposed to be initialized. I tried changing [line 623](https://github.com/alberanid/imdbpy/blob/58e9781afedcefe37865b614babb271fb55d8a70/imdb/parser/http/__init__.py#L623) to `data_d = {'data':{}}`, the `KeyError` is no longer thrown but the function just returns `{'data': {'number of episodes': 0}}`.

Maybe I need to fetch some other infosets for this to work? I am currently just using the default infosets. Obviously it works if I do `ia.update(s, 'episodes')` but then it is fetching all episodes - as I understand it the point of this method is to only fetch specific seasons.

**Comment by x11x** [comment]
My mistake, I see what the problem is now.
I just tried using a list of season nums instead of tuple as I was previously, i.e. `ia.update_series_seasons(s, season_nums=[10])` and it works.
I can see now how this can be fixed to support tuple of season numbers.
I will do a PR but this is probably not a huge issue as long as people know just to use a list.

**Comment by x11x** [comment]
I've fixed this. Another useful result of this is now you can do e.g. `ia.update_series_seasons(movie, season_nums=range(1, 7))`.

**Comment by alberanid** [comment]
PR merged; I've added your nickname to the credits, thanks!
