### ISSUE TITLE
Calling `update_series_seasons` for a movie that does not have any seasons raises a `IMDbDataAccessError (HTTP 404)

### ISSUE THREAD

**Issue by x11x** [alberanid/imdbpy#302]
#### Issue description

Discovered while working on #301 that currently calling `ia.update_series_seasons` (or `ia.get_movie_episodes`) for a movie that does not have any seasons raises a `IMDbDataAccessError` (HTTP Error 404 Not Found). Wonder if this should be changed to just silently setting 'episodes' to {} or None to match behaviour of using ia.update(movie, 'seasons').

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.9.1
- **IMDbPY:** 2020.12.20
- **OS:** Windows 10 10.0.18362 AMD64

Sorry don't have time to provide a code snippet at the moment

**Comment by x11x** [comment]
I just realized `update(movie, info=["episodes"])` does the same thing, so its not inconsistent. Maybe this is not an issue then.

**Comment by alberanid** [comment]
I agree that this behaviour is acceptable. If there are no other ideas to improve this, I would close it.

**Comment by x11x** [comment]
Thanks for your reply. I think raising an error is the right thing to do here to remind us to guard calls to update_series_seasons behind checking if 'kind' property is appropriate. sorry to waste your time with this one.
