### ISSUE TITLE
Every episode of a series runtime

### ISSUE THREAD

**Issue by stormaref** [alberanid/imdbpy#307]
#### Issue description

How can I get every episode runtime

#### Version of IMDbPY, Python and OS

**NOTICE: please always try the latest version from the repository before submitting a bug.**

- **Python:** python3 -v 3.9
- **IMDbPY:** 2020.09.25
- **OS:** windows 10

I just cannot get every episode runtime of a series it just give me a runtime for series

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python

# your code here
```

#### What's the expected result?

- 

#### What's the actual result?

- 

#### Additional details

-

**Comment by Philippe-Cholet** [comment]
```python
import imdb
from imdb.helpers import sortedEpisodes

api = imdb.IMDb()
results = api.search_movie('Lucifer')
luci = results[0]
# Get every episode of the TV show Lucifer (not fast)
api.update(luci, ['episodes'])
episodes = sortedEpisodes(luci)
# Currently "episodes" have minimal informations,
# get more information for each episode may be slow.
for ep in episodes:
    api.update(ep, ['main'])
# Now runtimes are available. ep['runtimes'] is a list of one runtime.
# "if 'runtimes' in ep" is there to discard not aired episodes.
runtimes = [int(ep['runtimes'][0]) for ep in episodes if 'runtimes' in ep]
# Obviously, "ep" contains much more informations that might be useful to you.
```

**Comment by alberanid** [comment]
I think the detailed answer by @Philippe-Cholet (thanks!) solves this issue; if not, please add a comment.
