### ISSUE TITLE
Get nothing from movie connections infoset

### ISSUE THREAD

**Issue by julthep** [alberanid/imdbpy#308]
#### Issue description

`connections` infoset get nothing from every title  

#### Version of IMDbPY, Python and OS

- **Python:** Python 3.7.7
- **IMDbPY:** 2020.09.25
- **OS:** Windows 10.0.18362

#### Steps to reproduce the issue

```
#!python

movie = ia.get_movie('0114709', info='connections')
movie.items()
```

#### What's the expected result?

- Movie connections data as shown in IMDb page: https://www.imdb.com/title/tt0114709/movieconnections

#### What's the actual result?

- `[]` (empty list)

#### Additional details

- Unable to find the explanation about this infoset in IMDbPY document.

**Comment by alberanid** [comment]
I confirm the bug.  I will try to work on it in the next few days or weeks.  Thanks for the report.

**Comment by alberanid** [comment]
it took me a long time, but it should be now fixed in version 2021-07-10

**Comment by julthep** [comment]
It still worked yesterday, but due to the IMDb Connections page being changed today, it not working anymore from now on.

**Comment by alberanid** [comment]
@julthep seems to work fine for me.

Test code:
```
#!python

movie = ia.get_movie('0114709', info='connections')
print(movie.items())
```

if you still face a problem, feel free to open a new issue.

Thanks!

**Comment by julthep** [comment]
@alberanid after IMDb changed the Connections page layout, it sometimes got the results but sometimes did not. It may depend on which server our cinemagoer session currently opens a connection to; the old layout page or the new layout page.

Test code:
`for i in range(10):
    movie = ia.get_movie('0114709', info='connections')
    print(i, len(movie['connections']))`

My result:
`0 10
1 10
2 0
3 10
4 0
5 10
6 10
7 0
8 0
9 0`

**Comment by julthep** [comment]
Already open a new issue (#436) as per your advice.
