### ISSUE TITLE
Series 'creator' parser broken (again?)

### ISSUE THREAD

**Issue by vredesbyyrd** [alberanid/imdbpy#309]
#### Issue description

series `creator` key is not present on any series, on the 25+ series i tried anyway. 

#### Version of IMDbPY, Python and OS

**NOTICE: please always try the latest version from the repository before submitting a bug.**

- **Python:** `Python 3.9.2` 
- **IMDbPY:** `2020.09.25`
- **OS:** `system='Linux', node='archlinux', release='5.11.6-1-ck-skylake', version='#1 SMP PREEMPT Thu, 18 Mar 2021 00:59:21 +0000', machine='x86_64''

#### Steps to reproduce the issue

```
series = ia.get_movie('0106179')
series['creator']
```

#### What's the expected result?

A list of the series creator(s)

`[<Person id:0004810[http] name:_Chris Carter_>]`

#### What's the actual result?

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.9/site-packages/imdb/utils.py", line 1503, in __getitem__
rawData = self.data[key]
```

#### Additional details

I was not sure if I should even open this since issue #275 appears to have resolved this. But sometime in the last two weeks the series `creator` key has seemingly broken, for me at least.  

`series.keys()` returns the following: 

```
['original title', 'cast', 'genres', 'runtimes', 'countries', 'country codes', 'language codes', 'color info', 'aspect ratio', 'sound mix', 'box office', 'certificates', 'number of seasons', 'rating', 'votes', 'cover url', 'imdbID', 'plot outline', 'languages', 'title', 'year', 'kind', 'series years', 'akas', 'seasons', 'writer', 'production companies', 'distributors', 'special effects', 'other companies', 'plot', 'canonical title', 'long imdb title', 'long imdb canonical title', 'smart canonical title', 'smart long imdb canonical title', 'full-size cover url']
```

**Comment by alberanid** [comment]
Hi, thanks for the report.

I fear there is not much we can do, since that specific information seems to be (sometimes?) missing from the /reference page.

As always, any improvement is welcome.

**Comment by vredesbyyrd** [comment]
No sweat. I get it. Ill close this issue. 

Thanks for your time!
