### ISSUE TITLE
Importing data has broke in the latest commit

### ISSUE THREAD

**Issue by deanc** [alberanid/imdbpy#31]
Commit: https://github.com/alberanid/imdbpy/commit/170251d5fb820201bc5e9dfb8165302597b78743

`python imdbpy2sql.py --mysql-force-myisam -d ~/Downloads/imdb-data/ -u mysql://user@localhost:/imdb-data`

> Traceback (most recent call last):
>   File "imdbpy2sql.py", line 3074, in <module>
>     run()
>   File "imdbpy2sql.py", line 2939, in run
>     readMovieList()
>   File "imdbpy2sql.py", line 1533, in readMovieList
>     mid = CACHE_MID.addUnique(title, yearData)
>   File "imdbpy2sql.py", line 1137, in addUnique
>     else: return self.add(key, miscData)
>   File "imdbpy2sql.py", line 1012, in add
>     self[key] = c
>   File "imdbpy2sql.py", line 921, in __setitem__
>     self.flush()
>   File "imdbpy2sql.py", line 975, in flush
>     self.flush(quiet=quiet, _recursionLevel=_recursionLevel)
>   File "imdbpy2sql.py", line 975, in flush
>     self.flush(quiet=quiet, _recursionLevel=_recursionLevel)
>   File "imdbpy2sql.py", line 975, in flush
>     self.flush(quiet=quiet, _recursionLevel=_recursionLevel)
>   File "imdbpy2sql.py", line 976, in flush
>     self._tmpDict = secondHalf

**Comment by alberanid** [comment]
so far I'm unable to reproduce it; do you have any additional output, for that traceback?

**Comment by alberanid** [comment]
Ok, I've noticed the error.  If you try it, let m know if it works.

Thanks!
