### ISSUE TITLE
Getting HTTPError 503: 'Service Unavailable

### ISSUE THREAD

**Issue by AndrejusAnto** [alberanid/imdbpy#311]
#### Issue description

*Getting HTTPError 503: 'Service Unavailable and doh error via browser, seems like something change in imdb api since april, i am using threading in my script, not sure what info to provide*

- **Python:** `Miniconda Python 3.8.8`
- **IMDbPY:** `2021.02.24` 
- **OS:** `Windows 10`

**Comment by alberanid** [comment]
hi @AndrejusAnto 

A 503 error is usually a problem server-side.

Please provide a minimal script to reproduce the problem.

Thanks.

**Comment by AndrejusAnto** [comment]
Sorry, to clarify: I have not change anything in my script and have tested with old pip version and new github version, so maybe it is not imdbpy problem?

**Comment by alberanid** [comment]
hard to tell, without a minimal script to reproduce the problem.  My guess is a network problem.

**Comment by AndrejusAnto** [comment]
```
import imdb
ia = imdb.IMDb()
from threading import Thread

watchseries = [
	"Attack on Titan",
	"Better Call Saul",
	"Black Mirror",
	"Brooklyn Nine-Nine",
	"Killing Eve",
	"Lucifer",
	"One Punch Man",
	"Star Trek: Picard",
	"Stranger Things",
	"The Blacklist",
	"The Good Doctor",
	"The Grand Tour",
	"The Mandalorian",
	"The Orville",
	"The Outsider",
	"The Witcher",
	"Sherlock",
	"True Detective",
	"Westworld",
	"Goliath",
	"Doom Patrol",
	"F Is for Family",
	"The Boys",
	"The Expanse",
	"The Umbrella Academy",
	"Altered Carbon",
	"Curb Your Enthusiasm",
	"His Dark Materials",
	"WandaVision",
	"Warrior",
	"Avenue 5",
	"Superman and Lois",
	"The Falcon and the Winter Soldier",
	"Dexter",
]

def collect_series(tv, idx):
    tvseries = ia.search_movie(tv)
    ifserie = True
    for serie in tvseries:
        if ifserie:
            seriesid = serie.movieID
            serieinfo = ia.get_movie(seriesid)
            serieyear = serieinfo["series years"]
            if ("tv" and "series") in serieinfo['kind'] and tv == serieinfo['title']:
                print(idx, tv, serieyear)
                ifserie = False
                ia.update(serieinfo, 'episodes')
                seasonlist = [s for s in sorted(serieinfo['episodes'].keys()) if s > 0]
                for s in seasonlist:
                    print("episodes number", len(serieinfo['episodes'][s]))

threads = []
for i, tvserie in enumerate(watchseries):
#     print(tvserie)
    threads.append(Thread(target=collect_series, args=(tvserie,i)))
for thread in threads:
    thread.start()

for thread in threads:
    thread.join()
```

**Comment by alberanid** [comment]
it works with shorter lists, but fails with the one you provided.

I've not looked into the returned error, but I'm 99% confident that the problem is that you are doing too many queries at the same time, and you hit a limit of the server.

Try running at most X queries in parallel.

The best approach, in my opinion, would be to use a pool of workers from the Python multiprocessing module: https://docs.python.org/3/library/multiprocessing.html

Hope this helps.

**Comment by alberanid** [comment]
Closed, since it was a network problem.
