### ISSUE TITLE
"get_movie_list" script is missing

### ISSUE THREAD

**Issue by Philippe-Cholet** [alberanid/imdbpy#315]
#### Issue description

Once imdbpy installed, I can't use the script `get_movie_list` because it is not in the variable "scripts" in the "setup.py".

#### To reproduce the issue

`get_movie_list`

#### Possible solutions in `setup.py`

- Just add `'./bin/get_movie_list.py'` in the variable `scripts`.
- Or `import glob` then `scripts = glob.glob('./bin/*.py')` instead of the big list. That way, you can't forget a script anymore.

**Comment by alberanid** [comment]
thanks for the notice, fixed!
