### ISSUE TITLE
imdbpy is safe to use in android app? 

### ISSUE THREAD

**Issue by Sahil-pixel** [alberanid/imdbpy#316]
can i use imdbpy module in  free android app and publish in goole play store?

is there any   law  violation ? can any one tell me please .is there any copyright issue ?

**Comment by alberanid** [comment]
A "real" answer can only be provided by a lawyer with a good knowledge on copyright issues, and greatly depends on your specific case.

The data is propriety of IMDb, released under various licenses; we just provide the code to manipulate it.

At the bare minimum, for sure you are not allowed to redistribute them and in no case you should gain anything from them (so, no ads in the app for example).

For a more articulated answer see https://github.com/alberanid/imdbpy/issues/295#issuecomment-736537467

**Comment by Sahil-pixel** [comment]
Thanks for this clarification.
