### ISSUE TITLE
prioritize a language when searching for a movie

### ISSUE THREAD

**Issue by eurusdagr** [alberanid/imdbpy#317]
i'm building a huge rep of japanese subtitles and i'm currently using imdbpy to retrieve the directors name and organize my folder more easily, so my question is: is there a way for me to tell the api to prioritize movies in japanese than in other languages? sometimes it works if I just add "japanese" to the search but it's not always.

https://github.com/eurusdagr/subtitle-organizer/blob/main/subtitleorganizer.py, this is my current code, i'm definitely not good in python so if you want to leave any sugestions too you can.

**Comment by Philippe-Cholet** [comment]
Did a test with Princess Mononoke
```python
>>> m = api.get_movie(api.search_movie('Princess Mononoke')[0].getID())
# I looked for "japan" informations.
>>> m['language codes']
['ja']
>>> m['countries']
['Japan', 'United States']
>>> m['country codes']
['jp', 'us']
>>> m['languages']
['Japanese']
```
So instead of `movie = movie[0].getID()`, maybe something like that
```python
selected_movie = movie[0]  # first by default
for m in movie:
    if 'jp' in m.get('country codes', []):  # or use another key
        selected_movie = m
        break
movie = selected_movie.getID()
```

**Comment by eurusdagr** [comment]
oooh cool! thank you, i'm going to try to implement that on the weekend and see if works, thank you again!

**Comment by eurusdagr** [comment]
still does'

> 
> 
> Did a test with Princess Mononoke
> 
> ```python
> >>> m = api.get_movie(api.search_movie('Princess Mononoke')[0].getID())
> # I looked for "japan" informations.
> >>> m['language codes']
> ['ja']
> >>> m['countries']
> ['Japan', 'United States']
> >>> m['country codes']
> ['jp', 'us']
> >>> m['languages']
> ['Japanese']
> ```
> 
> So instead of `movie = movie[0].getID()`, maybe something like that
> 
> ```python
> selected_movie = movie[0]  # first by default
> for m in movie:
>     if 'jp' in m.get('country codes', []):  # or use another key
>         selected_movie = m
>         break
> movie = selected_movie.getID()
> ```

I'm currently trying this 
`import imdb
ia = imdb.IMDb()

movie = ia.search_movie("Alleycats")
selected_movie = movie[0]
for m in movie:
    if 'ja' in m.get('language codes', []):  
     selected_movie = m

movie = selected_movie.getID()
movie = ia.get_movie(movie)
print(movie)
`
And somehow even if the movie doesn't have the language codes "jp" it still gets passed through, this one above it's just a test for me to see

**Comment by eurusdagr** [comment]
I found a way to make it work!
'''        for m in movie:
            movie = m.getID()
            movie = ia.get_movie(movie)
            if 'ja' in movie.get('language codes', []):  # or use another key
                selected_movie = m
                break '''
I have to basically get all the information of the movie so I could be able to check every single one of them, it's really slow but it works so i'm fine with it
