### ISSUE TITLE
http: "kind" inconsistent between search_movie() and get_movie()

### ISSUE THREAD

**Issue by letmaik** [alberanid/imdbpy#318]
#### Issue description

The `"kind"` field returned by `search_movie()` is "tv miniseries" while for `get_movie()` it is "tv mini series".

#### Version of IMDbPY, Python and OS

- **IMDbPY:** 2021.4.18

#### Steps to reproduce the issue

```
from imdb import IMDb
movies = IMDb().search_movie("capture 2019")
print(movies[1]['kind']) # tv miniseries
movie = IMDb().get_movie(8201186)
print(movie['kind']) # tv mini series
```

**Comment by alberanid** [comment]
it should be fixed in the repository, thanks for the report!
