### ISSUE TITLE
TV series directors and writers

### ISSUE THREAD

**Issue by hpierce** [alberanid/imdbpy#321]
#### Issue description

I can get directors and writers from movies, assuming they have them, but it won't give me them for TV shows.

#### Version of IMDbPY, Python and OS
python3-imdbpy 6.8-2
Linux 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Python 3.8.5

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```
#!python
from imdb import IMDb
ia = IMDb()
movie = ia.get_movie('0443390')
print(movie['title'])
if movie.get('directors'):
    for director in movie['directors']:
        print(director['name'])

#### What's the expected result?
Love Soup
Christine Gernon
Sandy Johnson
- 


#### What's the actual result?
Love Soup

- 


#### Additional details

-

**Comment by alberanid** [comment]
Hi, sorry for the long delay.

The information about directors is not available on TV series; IMDbPY parses the **/reference** page; e.g.: https://www.imdb.com/title/tt0443390/reference

Closing this issue, since as far as I know there is nothing we can do about it.

**Comment by hpierce** [comment]
Thank you.
