### ISSUE TITLE
Keyword results are always 'movie' kind

### ISSUE THREAD

**Issue by thedjdoorn** [alberanid/imdbpy#326]
#### Issue description

All of the results from the get_keyword method contain a 'kind' field that is always 'movie', even when it's not a movie

#### Version of IMDbPY, Python and OS

- **Python:** 3.9.6
- **IMDbPY:** 2021.04.18
- **OS:** Arch Linux (5.12.14-arch1-1)

#### Steps to reproduce the issue
```python
#!python
from imdb import IMDb

examples = {
    "adult-animation": "0096697",  # The Simpsons
    "bristol-england": "0840196",  # Skins UK
    "social-anxiety-disorder": "4158110",  # Mr. Robot
    "matrix": "0277828"  # Enter the Matrix (Video Game)
}
ia = IMDb()

for key in examples:
    results = ia.get_keyword(key)
    result = [r for r in results if r.movieID == examples[key]][0]
    print(result['kind'])

```

#### What's the expected result?

```
tv show
tv show
tv show
video game
```

#### What's the actual result?

```
movie
movie
movie
movie
```

<sub>PS: Consider enabling syntax highlighting in the issue template :)</sub>

**Comment by alberanid** [comment]
thanks for the report.

Problem is, the information is not present in the page (e.g. https://www.imdb.com/search/keyword/?keywords=bristol-england ) so we have no way to tell if it's a movie or a tv series or something else.

Closing this issue; if someone find a way to solve the problem, feel free to reopen it.

PS: thanks for the hint about the syntax highlighting, I've updated the template
