### ISSUE TITLE
synopsis are shown as one large string with paragraph "information" removed.

### ISSUE THREAD

**Issue by toasta** [alberanid/imdbpy#327]
#### Issue description

not really a bug, just a possible improvement.

https://github.com/alberanid/imdbpy/blob/master/imdb/parser/http/movieParser.py#L875
currently gets rid of all non-text nodes.

imdb seems to separate their paragraphs by `<br><br>`. Those get lost and
all the plot/synopsis end up as one giant string with no paragraph information
or correct "spacing" (" " after "." for example, if it's on a paragraph-break)

#### Version of IMDbPY, Python and OS

should not matter.

- **Python:** 3.8.10
- **IMDbPY:** IMDbPY-2021.7.10, 2021.4.18, and-the-one-before... don't recall which one.
- **OS:** `system='Linux', release='5.4.0-77-generic', version='#86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021', machine='x86_64', processor='x86_64')`

#### Steps to reproduce the issue

```
#!python
import imdb
imdb_id = 1270797
ia = imdb.IMDb('https')
tm = ia.get_movie(imdb_id)
xml=tm.asXML()
print(xml)
```
pipe that trough
```xmllint --pretty 1 - | grep ' CARNAGE.Post' | grep --colour -P ".\.\S"```

most colored things should have at least one newline or a space behind the .

#### What's the expected result?

- synopsis/item should at least preserve newlines or even better, return `<item/>` for each paragraph.

#### What's the actual result?
 
- the entire synopsis is squashed into one string. Where the two `<br>`s were, even spaces are removed (eg: ' CARNAGE.Post-Credits: ')

#### Additional details

i tried patching imdb/parser/http/movieParser.py

```
@@ -45,7 +45,7 @@
 from imdb.Person import Person
 from imdb.utils import _Container, KIND_MAP

-from .piculet import Path, Rule, Rules, preprocessors, transformers
+from .piculet import Path, Rule, Rules, preprocessors, transformers, ElementTree
 from .utils import DOMParserBase, analyze_imdbid, build_person, build_movie

 if PY2:

@@ -847,6 +847,12 @@
         result = pparser.parse(plot_summary_html_string)
     """
     _defGetRefs = True
+    def synopsis_reducer(nodes):
+      ret=[]
+      for n in nodes:
+        if type(n) is ElementTree._ElementUnicodeResult:
+          ret.append(n)
+      return ret

     # Notice that recently IMDb started to put the email of the
     # author only in the link, that we're not collecting, here.
@@ -872,11 +878,13 @@
             key='synopsis',
             extractor=Path(
                 foreach='//ul[@id="plot-synopsis-content"]',
-                path='.//li//text()'
+                path='.//li//node()',
+                reduce=synopsis_reducer,
             )
         )
     ]

+
```

to get rid of the lxml text() handling (i think it's that, not the default piculet-concat reducer)
and replace it by something only looking for unicode-text-elements and pushing
those to an array.

this works, only blemish is that in the xml the whole synopsis get an additional
`<item/>` pair around it, but that might just be the special toXML() handling... 
I read something about not returning arrays for specific keys (which is imho sometimes
cumbersome if you've to check the type of items you are going to use, but i see the
"convenience" if not using it in a general case)

I'd prefer to have an array so i can style the paragraphs in whatever language i want
just by iterating over the `<items/>`, but that might break existing code which parses/stores
the xml and uses an xpath to access the synopsis.

Maybe a constructor switch like "always_return_arrays=True" or something like that would be nice?

To not break existing stuff, one could replace all non _ElementUnicodeResult nodes with "\n"
and return again a single string; this would at least give any renderer a chance to display
this a bit more readable.

I did not have the chance to check if this works if lxml is not used and piculet falls
back to xml.

I was thinking about modifying the tree in a preprocessor, either pretty by returning a new
tree or by just replacing the `<br><br>` with something like `</item><item>` but that
seemed to ugly, even for me.

Thx for this awesome module and all the time you put into it!

**Comment by alberanid** [comment]
@toasta thanks!

I'm not too sure that a list of paragraphs is what the users expect.

Right now I've introduced your code, but returned a string that preserves the newlines.

Anyway, I'm open to other changes, if they are useful in other cases.

Thanks!
