### ISSUE TITLE
One Piece not passable caused by year order instead of seasons

### ISSUE THREAD

**Issue by 9Mad-Max5** [alberanid/imdbpy#330]
#### Issue description

*Series which are listed like One Piece lead to the below attached issue.
As I'm not the maintainer of the program which run in to the issue im not sure about the exact command.*

#### Version of IMDbPY, Python and OS

**NOTICE: please always try the latest version from the repository before submitting a bug.**
https://github.com/rix1337/docker-feedcrawler

- **Python:** `3.6.9`
- **IMDbPY:** `2021.04.18`
- **OS:** `uname_result(system='Linux', node='44dc9642e04d', release='4.14.24-qnap', version='#1 SMP Mon Jul 26 06:10:33 CST 2021', machine='x86_64', processor='')`
- 

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

The normal expected request against imdb:
https://www.imdb.com/title/**imdbid**/episodes?season=1

The expected request against the server:
https://www.imdb.com/title/tt0388629/episodes?year=1999

#### What's the expected result?

- 

#### What's the actual result?

- Traceback (most recent call last):, File "/usr/lib/python3.6/site-packages/feedcrawler/crawler.py", line 126, in crawler, task.periodical_task(), File "/usr/lib/python3.6/site-packages/feedcrawler/sites/content_all_dw.py", line 79, in periodical_task, shared_blogs.periodical_task(self), File "/usr/lib/python3.6/site-packages/feedcrawler/sites/shared/content_all.py", line 885, in periodical_task, found = search_imdb(self, desired_rating, parsed_url), File "/usr/lib/python3.6/site-packages/feedcrawler/sites/shared/content_all.py", line 185, in search_imdb, if imdb_data.data["votes"] < 1500:, KeyError: 'votes', 2021-08-31 07:54:30,232 CRITICAL [imdbpy] /usr/lib/python3.6/site-packages/imdb/_exceptions.py:34: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0388629/episodes?season=1', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 400: ''>},); kwds: {}, Traceback (most recent call last):, File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 220, in retrieve_unicode, response = uopener.open(url), File "/usr/lib/python3.6/urllib/request.py", line 532, in open, response = meth(req, response), File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response, 'http', request, response, code, msg, hdrs), File "/usr/lib/python3.6/urllib/request.py", line 570, in error, return self._call_chain(*args), File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain, result = func(*args), File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default, raise HTTPError(req.full_url, code, msg, hdrs, fp), urllib.error.HTTPError: HTTP Error 400: , 2021-08-31 07:54:30,233 CRITICAL [imdbpy] /usr/lib/python3.6/site-packages/imdb/__init__.py:792: caught an exception retrieving or parsing "episodes" info set for mopID "0388629" (accessSystem: http), Traceback (most recent call last):, File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 220, in retrieve_unicode, response = uopener.open(url), File "/usr/lib/python3.6/urllib/request.py", line 532, in open, response = meth(req, response), File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response, 'http', request, response, code, msg, hdrs), File "/usr/lib/python3.6/urllib/request.py", line 570, in error, return self._call_chain(*args), File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain, result = func(*args), File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default, raise HTTPError(req.full_url, code, msg, hdrs, fp), urllib.error.HTTPError: HTTP Error 400: , , During handling of the above exception, another exception occurred:, , Traceback (most recent call last):, File "/usr/lib/python3.6/site-packages/imdb/__init__.py", line 787, in update, ret = method(mopID), File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 631, in get_movie_episodes, self.urls['movie_main'] % movieID + 'episodes?season=' + str(season), File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 378, in _retrieve, ret = self.urlOpener.retrieve_unicode(url, size=size), File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 254, in retrieve_unicode, 'original exception': e}, imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0388629/episodes?season=1', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 400: ''>}, [Ombi] - Fehler beim Abruf der IMDb für: 0388629,

#### Additional details

-

**Comment by rix1337** [comment]
Basically: This line will cause a CRITICAL error for tv shows that have no seasons listed, but years.
https://github.com/alberanid/imdbpy/blob/e162cf90109438fc1c9ae1487582d257e0428e68/imdb/parser/http/__init__.py#L633

**Comment by alberanid** [comment]
PR merged, thanks!

Just a question, since I had no time to verify: skipping those seasons are we missing some information? If yes, is there a way to correctly fetch all of the seasons?

**Comment by rix1337** [comment]
Thanks for the quick merge.

Basically when both try/catches are necessary, we will pass whatever season count was found to the movie result instance.

This is better than nothing but not really usable.

A real fix would be parsing seasons by year instead of season count when the attempt fails.

I was not able to find a streamlined way to do this.

My 5 cents:
When we run into this error the results from IMDb are not really usable in 3rd party apps anyway so the try/catch sould be enough.
