### ISSUE TITLE
--local-infile with MySQL?

### ISSUE THREAD

**Issue by beanumber** [alberanid/imdbpy#34]
I'm trying to use `imdbpy2sql`. When running 

```
imdbpy2sql.py --mysql-force-myisam -d ~/dumps/imdb/raw -u 'mysql://root:<password>@localhost/imdb' -c ~/dumps/imdb/raw
```

I get the following error:

```
loading CSV files into the database
 * LOADING CSV FILE /home/bbaumer/dumps/imdb/raw/complete_cast.csv...
ERROR: unable to import CSV file /home/bbaumer/dumps/imdb/raw/complete_cast.csv: (1148, 'The used command is not allowed with this MySQL version')
```

The problem is that the `--local-infile` flag on my client is not on. Now, if I was writing the command myself, I could just add `--local-infile=1` and it should work. But since `imdbpy2sql` is generating the `mysql` command for me, I can't add that option. 

Could you add that option? Or an option to pass-through additional arguments to `mysql`? 

Or is there a better solution? Any help would be appreciated. 

[BTW, I am working on a derivative R package. See (https://github.com/beanumber/imdb/issues/3)]

**Comment by beanumber** [comment]
Does `imdbpy2sql` read from the `my.cnf` file? This might be an elegant solution. I think you'd have to add something to line 549:
```
connectObject = conn.getConnection()
```
Is this helpful: (http://pythonpaste.org/archives/message/20060825.192841.d51e9ed5.pt.html)?

**Comment by alberanid** [comment]
I think we can add --local-infile somehow, but I'm not sure exactly when it should be used.  Isn't there an equivalent command to be issued in SQL?

If yes, we can try a solution with the -e command.  See http://imdbpy.sourceforge.net/docs/README.sqldb.txt (ADVANCED FEATURES section)

**Comment by alberanid** [comment]
This issue is even more valid with the new, Python 3, release.

The state of MySQL modules for Python seems a little sorry.  MySQLdb-python is basically unsupported, right now.  Others, like pyconnector and pymysql, seem to ignore the local-infile option (that I had to remove from the code).

If anyone knows of a working solution, some help is welcome.

**Comment by alberanid** [comment]
Closing it, since IMDb stopped updating the old dataset and the new one is much easier to parse and import.
