### ISSUE TITLE
Where to find more usage examples?

### ISSUE THREAD

**Issue by SeaDude** [alberanid/imdbpy#359]
#### Issue description

The docs have only a sparse example of how to use this tool. Are there any other resources that cover detailed usage?

**Example:**
- By scouring these GitHub issues, I learned that `ia.get_movie('1677720').data['cover url']` is how to pull cover art form a movie.
- Unless I'm missing it, this is not in the docs

**Comment by alberanid** [comment]
Most (ok, _some_) of the keys are not defined in the code, but they are taken from dynamic sections of the web pages we parse: this would make it difficult to provide an example for each kind of data.

The most important concept to keep in mind is that we parse **information sets**: https://imdbpy.readthedocs.io/en/latest/usage/data-interface.html

Once you know which information sets are available (`get_movie_infoset`, get_person_infoset`) and which are parsed by default (`default_info`) you can decide the ones to fetch (on `get_movie`, `get_person` and on `update` calls).

Once you have fetched more information sets, you can tell which keys came from which info set with `infoset2keys` and, in general, get the complete list of available keys with `keys()`.

Having said that, obviously any improvement to the documentation is welcome.

Hope this help.

**Comment by SeaDude** [comment]
Thank you for the quick reply. The use of `infoset2key` and `keys()` really clicked for me. 

One little thing, I noticed a typo in the response from `keys()` : `'costume departmen'` vs. `costume department`. 

Cheers!
