### ISSUE TITLE
Step by step install imdbpy

### ISSUE THREAD

**Issue by beryindo** [alberanid/imdbpy#36]
Hi all, can u help me, step by step install imdbpy on ubuntu 14 ?

**Comment by alberanid** [comment]
Follow the instructions in http://imdbpy.sourceforge.net/docs/README.txt​

**Comment by bombolini** [comment]
At the end of installation on ubuntu 14.04, I receive below error:
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ZNL2Rc-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/lxml
Storing debug log for failure in /root/.pip/pip.log

fyi.

**Comment by alberanid** [comment]
are you sure that your virtualenv was created with a Python3 interpreter?

The correct command to create it is: `virtualenv -p python3`
