### ISSUE TITLE
Station Eleven (tv mini series) is recognized as `kind = movie`

### ISSUE THREAD

**Issue by sandrotosi** [alberanid/imdbpy#367]
#### Issue description

https://www.imdb.com/title/tt10574236/?ref_=ra_gb_ln

is recognized as a `movie` and not a `tv series`

#### Version of IMDbPY, Python and OS

- **Python:** 3.10.1
- **IMDbPY:** 2021.04.18
- **OS:** Debian unstable

#### Steps to reproduce the issue

```python
#!/usr/bin/env python

import imdb
ia = imdb.IMDb()
x = ia.search_movie('station eleven')
print(x[0]['kind'])
```

#### What's the expected result?

- `tv series`

#### What's the actual result?

- `movie`

**Comment by sandrotosi** [comment]
and another mini series detected as movie: https://www.imdb.com/title/tt11471892/ (landscapers)

**Comment by arshamalh** [comment]
My pull request solved this issue as well, you can check it out.
https://github.com/alberanid/imdbpy/pull/363

**Comment by alberanid** [comment]
I confirm this works now.

There are still some title types missing, as listed by https://www.imdb.com/search/title/ ; any PR to also support them is welcome.

**Comment by sandrotosi** [comment]
thanks@ @alberanid do you plan on releasing a new version soon? there are quite some changes since the last one in Aprli.

**Comment by alberanid** [comment]
> thanks@ @alberanid do you plan on releasing a new version soon? there are quite some changes since the last one in Aprli.

Not in the short time, I fear; maybe in two or three months.  Meanwhile, you can use the version from the repository - we have switched to a date-based version because the "release versions" tend to become obsolete quickly.
