### ISSUE TITLE
Importing to Sql Server - text has encoding issues

### ISSUE THREAD

**Issue by ericpopivker** [alberanid/imdbpy#37]
Hi,

Thank you very much for a great tool.

I am using it to import latest IMDB csv files to local Sql Server Express 2014 database.
When I look at the data in DB I see text like this in title.title.:

"A PrÃ³xima VÃ­tima"
"DiscriminaciÃ³n en el lenguaje"
...

In name.name  I see,

"Aarseth, Ã˜ystein"
"Abati, JoÃ«l"
...

Looks like something with encoding.  The command I use to import is:
python.exe imdbpy2sql.py-d C:\imdb-files -u "mssql://connection text" --ms-sqlserver

I am using Sql Server 2014 express.
What can I do to fix it?

Thank you,

Eric

**Comment by alberanid** [comment]
Hi,
it's almost surely a problem of encoding.  imdbpy2sql.py writes everything in UTF-8, so your database must be configured accordingly.

Unfortunately, I don't know how this could be done in SQL Server 2014.
