### ISSUE TITLE
Movie color info parsed incorrectly

### ISSUE THREAD

**Issue by uyar** [alberanid/imdbpy#51]
In the movie combined details page, the color info is parsed incorrectly for some titles. For the title with id '0063650' (the movie "If....") the color info is reported as ':(Eastmancolor) (uncredited)' when it should have been 'Color::(Eastmancolor) (uncredited)'

**Comment by alberanid** [comment]
Seems correct, now, for both 'color' and 'color info' (from the technical specs page).
