### ISSUE TITLE
Unicode error in actor names

### ISSUE THREAD

**Issue by sks147** [alberanid/imdbpy#52]
Movie ID : 0060196

Line 90 
```
for name in cast:
       print '      %s (%s)' % (name['name'], name.currentRole)
```
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 11: ordinal not in range(128)`

**Comment by rlnunez** [comment]
I was getting a similar error, the fix was to create a function that would return a blank string if the current role was null

```
def get_currentRole(data):
    return unicode(data.currentRole) or u''
```

**Comment by sks147** [comment]
@rlnunez Thanks!
