### ISSUE TITLE
Allow local database update

### ISSUE THREAD

**Issue by roipoussiere** [alberanid/imdbpy#53]
A very interesting feature of this project is the possibility to download a local copy of the whole imdb database.

But it could be more interesting to update this database without downloading it again, maybe by looking the [RSS feeds](https://www.rsssearchhub.com/feeds/imdb).

**Comment by alberanid** [comment]
it would be cool and useful, but there's no point in introducing it for the old dataset.  We may consider it designing the code for #60 

Thanks for the hint!
