### ISSUE TITLE
Timeout error IOError('socket error', timeout('timed out',))

### ISSUE THREAD

**Issue by parunach** [alberanid/imdbpy#54]
When I try

```
ia = imdb.IMDb()
s_result = ia.search_movie(title)
first = s_result[0]
# get synopsis                                                                                                                             
ia.update(first, 'synopsis')
```

I get this error in many cases

> CRITICAL [imdbpy] /usr/lib64/python2.7/site-packages/imdb/_exceptions.py:35: IMDbDataAccessError exception raised; args: ({'exception type': 'IOError', 'url': 'http://akas.imdb.com/title/tt0110647/combined', 'errcode': 'socket error', 'proxy': '', 'original exception': IOError('socket error', timeout('timed out',)), 'errmsg': 'timed out'},); kwds: {}

Any reason for this?

**Comment by alberanid** [comment]
Hi @parunach : being a timeout, it's most probably a problem on your network.

**Comment by parunach** [comment]
Can I try/except these errors?

**Comment by alberanid** [comment]
@parunach : I can't remember if it's just a warning or an exception.  If it's an exception, you can catch imdb.IMDbError
