### ISSUE TITLE
pep8

### ISSUE THREAD

**Issue by pmccauley1994** [alberanid/imdbpy#55]
Any Python repos should be formatted to adhere to pep8. 
https://www.python.org/dev/peps/pep-0008/

Some of the formatting standards are commonly ignored, however, such as
- E501: line too long - lines should only no more than 79 characters in length

**Comment by pmccauley1994** [comment]
after running 
`pep8 --ignore=E501 . | wc -l`
it shows there are 3445 formatting issues

**Comment by adveres** [comment]
>Any Python repos should be formatted to adhere to pep8.

While I happen to agree, it's incredibly contentious to dogmatically adhere to language style guidelines.

See [this StackOverflow](https://stackoverflow.com/questions/159720/what-is-the-naming-convention-in-python-for-variable-and-function-names), for example, where some devs say they deviate purposefully.

In any case, I'd like to contribute so I'll probably try and help out with this :)

**Comment by alberanid** [comment]
Pull request #59 seems to fix most of these problems; I'll probably merge it soon. :-)

**Comment by delirious-lettuce** [comment]
@alberanid ,

My PR #59 wasn't anywhere close to fixing every file in this repo. There are still many more PEP8 issues.

**Comment by alberanid** [comment]
true, but I don't want to break the API and for other fixes there's always time.  Thanks for the help!

**Comment by delirious-lettuce** [comment]
@alberanid ,

No problem, I just wanted to mention it since the issue was closed but it wasn't totally fixed yet.

Anyways, thanks for your time!
