### ISSUE TITLE
How to obtain the plot of a movie?

### ISSUE THREAD

**Issue by allenjack** [alberanid/imdbpy#56]
Hi,

My question maybe stupid, I am trying to obtain the plots of several movies, but I didn't find the right API to use.

I tried the following code:
the_matrix = ia.get_movie('0133093')
print the_matrix.get('plot outline')  # works for me
print the_matrix['plot'] # doesn't work for me

I am wondering what is the right way to get the plot outlines, summaries, and synopses?

**Comment by alberanid** [comment]
@allenjack : your code is correct; indeed it seems that the plot parser is bugged. :(

The DOMHTMLPlotParser class in imdb/parser/http/movieParser.py must be fixed. Unfortunately I won't be able to look at it for some time.

**Comment by mchristopher** [comment]
I think updating line 1925 of `parser/http/movieParser.py` to the following would work:
```py
path="//ul[@id='plot-synopsis-content'][not(@style)]"
```

There seem to be a bunch of subtle changes that IMDb has made to their HTML in addition to this change, so not sure if it should be part of a larger PR to get scraping updated.

**Comment by alberanid** [comment]
@mchristopher : thanks for the patch: I've included it; it fixes only the plot synopsis parser and not the "plot" parser, so I leave this issue open, for now.

**Comment by allenjack** [comment]
Thank you so much, it works like a charm.

**Comment by alberanid** [comment]
will be fixed with #66
