### ISSUE TITLE
Recieving imdb link in another format

### ISSUE THREAD

**Issue by jatinrajani** [alberanid/imdbpy#58]
After parsing twitter through its api .I am getting imdb link in this format https://t.co/pEoXfFP7Xc.So imdb id would be pEoXfFP7Xc.And after using ia.get_movie('pEoXfFP7Xc')it said format is invalid.

**Comment by alberanid** [comment]
@jatinrajani : that's a url from the shortner used by Twitter and you can't use it in IMDbPY, directly; maybe it's possible to resolve it in the real URL: see the API from https://t.co/

**Comment by jatinrajani** [comment]
Thank u for helping.☺☺
