### ISSUE TITLE
support for the new S3 dataset

### ISSUE THREAD

**Issue by alberanid** [alberanid/imdbpy#60]
IMDb has introduced a new alternative interface: http://www.imdb.com/interfaces

Now the files are stored in S3, and are more easier to process (there's also a lot less information than what was previously available).

We need a new access system to support the import of this data in a SQL database and retrieve them.

See also this thread: https://sourceforge.net/p/imdbpy/mailman/message/35922484/

**Comment by alberanid** [comment]
working on it in the https://github.com/alberanid/imdbpy/tree/issue-60-s3-dataset branch.
So far I have an importer, but still no way to access the data.

It's not really complicated, and I hope to have something that can be worked on soon (even if right now I'm busy on other projects)

**Comment by alberanid** [comment]
the feature was merged in master; it's still to be considered of beta quality, but (almost?) all the features should be there.

**Comment by andrisi** [comment]
@alberanid Will data from the new file format update a database created from the last dump in the old IMDB format, which had much more data on each movie? Thanks!

**Comment by alberanid** [comment]
@andrisi : unfortunately the two dataset are not compatible with each other and they can't be easily merged.

You can still download the last old-format dataset from ftp://ftp.funet.fi/pub/mirrors/ftp.imdb.com/pub/frozendata/ and use the old imdbpy2sql.py script to import it in a SQL database (and then use the "sql" data access method of IMDbPY to access them, instead of the new "s3")

**Comment by andrisi** [comment]
@alberanid You mean you'll abandon the old, and just start with a new schema eventually? I don't really see how they're incompatible. It's more like the one on S3 has less tables - but it's essentially the same source database. You do have IMDB IDs in the old somehow too, right? I might be able to help, but need to see what's your view on this.

**Comment by alberanid** [comment]
@andrisi : as always, any help is welcome!

There are various problems, here: first of all, neither "sql" nor "s3" have the concept of "update".  In both cases, the whole db is deleted and rebuilt, importing a newer set of data (in "sql" I take care to preserve the IMDb IDs, if possible).
The other problem is that by default on "sql" the IMDb IDs are missing, by default; they are just inserted in some very special cases, when a query to the site is made for other reasons.

So... an update is quite difficult to implement, especially between the two dataset.
It would be easier just for "s3", but since the import is quite fast, I'm not sure it's worth the effort.

What do you think?

**Comment by andrisi** [comment]
@alberanid I see... I thought this rebuild-from-scratch is just the defaul option, but you have updates too. Hmmm. So you don't have the IMDB IDs in the "sql" version. I'd probably use the "s3" source to adds all IDs to the db built by the "sql" source, and then start updating the db from the "s3" source. Let me finish building the the "sql' db, and then I'll think about it in more detail.

**Comment by alberanid** [comment]
@andrisi : great!  Expect the import process of the old dataset to take many hours, especially during the creation of indexes.

Some hints that may help:
- if you are not familiar with it, the db schema can be found in imdb.parser.sql.dbschema
- as said, the IMDb IDs are not present in the dataset
- the _title.title_ column contains the title without imdbIndex, production year and so on (basically, it should be the same title you find in the s3 dataset)
- the _title.md5sum_ column contains a md5 of the complete title, meaning that it includes also imdbIndex and year, making it impossible to use this field as a map between the two dataset (plus, m5sum is not present in s3, at the moment)

So to match between "sql" and "s3" you probably need to look for the whole title.
The main problems with upgrades is that you need to consider three cases: when new data is added, when data is removed and when data is modified.
Not so easy. :-)

Let me know if you need help.  You can also subscribe the imdbpy-devel mailing list (very low traffic): https://sourceforge.net/projects/imdbpy/lists/imdbpy-devel
