### ISSUE TITLE
Movie IMDb index in search results not parsed

### ISSUE THREAD

**Issue by uyar** [alberanid/imdbpy#68]
Instead, the IMDb index becomes part of title. For example, search for the title "blink". The result includes an item "Blink (IV)". This text is interpreted as the title of the movie instead of the title being "Blink" and adding an imdbIndex key with the value "'IV".

**Comment by alberanid** [comment]
Confirmed.  It seems that there's another new format for movie titles, and now the result page contains stuff like "The Agent (II) (2008) (Short)"

I'll fix it soon.

**Comment by alberanid** [comment]
Fixed and ported to old master, too.
