### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0

### ISSUE THREAD

**Issue by veeralpatel** [alberanid/imdbpy#73]
Getting the following error when running the sample provided in the README.

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
`

**Comment by rohuns** [comment]
The article that it is failing on is "Ï"

**Comment by alberanid** [comment]
Hi,
thanks for the report!

Can you try using the version from Github?  At the moment I'm unable to reproduce it.

Code:
```
from imdb import IMDb
ia = IMDb()

# print the director(s) of a movie
the_matrix = ia.get_movie('0133093')
print(the_matrix['director'])

# search for a person
for person in ia.search_person('Mel Gibson'):
    print(person.personID, person['name'])
```

Output:
```
[<Person id:0905154[http] name:_Wachowski, Lana_>, <Person id:0905152[http] name:_Wachowski, Lilly_>]
0000154 Mel Gibson
2153167 Mel Gibson
0317112 Mel Gibson
6709224 Mel Gibson
3323885 Adam Taylor
2800055 Mel Gibson
0316945 Donal Gibson
2106809 Raquel Gibson
0317195 Terel Gibson
3912400 Jamel Gibson
0316878 Cal Gibson
7133936 Jamel Gibson
7699405 Jamel Gibson
0316950 E.L. Gibson
2798174 Daniel Gibson
4047961 Noel Gibson
2988370 Mal Gibson
1270944 Paul Gibson
9235742 Daniel Gibson
0316915 Daniel Gibson
```

**Comment by rohuns** [comment]
Just pulled and getting the same issue. There is some UTF-8 encoding isue with the set of characters that I posted before. Here is the traceback and am using python 2.7.10. Let me know if this is helpful and if there is anything else I can provide.
<img width="719" alt="screen shot 2017-11-13 at 10 43 25 am" src="https://user-images.githubusercontent.com/17604744/32742883-9278427e-c85f-11e7-8a80-6fa1ac5b48f5.png">

**Comment by alberanid** [comment]
Hi @rohuns : the new release of IMDbPY (6.x and later) can only run with Python 3. :-)

If you need the old version, you can use the https://github.com/alberanid/imdbpy/tree/imdbpy-legacy branch.

I will introduce a warning in both versions, to notify the users.

**Comment by alberanid** [comment]
notice introduced in #78
