### ISSUE TITLE
Add a command line interface

### ISSUE THREAD

**Issue by uyar** [alberanid/imdbpy#81]
Implement a CLI that would encompass the functionality provided by the current script. An example use could be something like: "imdb-cli search movie matrix", or "imdb-cli get person 1".

**Comment by alberanid** [comment]
that would be really cool!

**Comment by NightMachinary** [comment]
What happened to this CLI?

**Comment by uyar** [comment]
It has been implemented but it's called "imdbpy". Try running "imdbpy --help".

**Comment by NightMachinary** [comment]
Thanks!
I think the CLI can use some interactivity? The current workflow seems to
be “imdbpy search movie MOVIENAME” and then “imdbpy get movie ID” which is
rather bothersome. If it allowed us to just choose the movie to get in the
search itself, things would be simpler. Also, having an “—auto-choose”
option would be nice; It’d just gets the most popular item of the search;
E.g., “imdbpy search —auto-choose jaws” returns the Jaws. :D (Which is the
first item in the search, so implementing this might be all that hard.)

**Comment by uyar** [comment]
There is a `--first` option that might help:

`imdbpy search movie --first jaws`

Other than that, a more interactive CLI rather than a one-shot CLI would be nice. Based on `cmd` without any external dependencies, or based on something like `python-prompt-toolkit`. But with external dependencies, it would probably be a better idea to make it a separate project.
