### ISSUE TITLE
Person bio parser cannot get some of the data

### ISSUE THREAD

**Issue by uyar** [alberanid/imdbpy#93]
#### Issue description

The person bio parser cannot get the birth date, death date, nicknames correctly.

#### Version of IMDbPY, Python and OS

- **Python:** 3.4.7
- **IMDbPY:** 6.3dev20171119
- **OS:** Linux (Mint 18.2 XFCE)

#### Steps to reproduce the issue

```
#!python

ia = imdb.IMDb()
julia_roberts = ia.get_person_biography('0000210')
julia_roberts['data'].keys()
```

#### What's the expected result?

- birth date, birth notes, death date, death notes, birth name, nick names, height, spouse, mini-biography, trivia, trade mark, salary

#### What's the actual result?

- only birth notes, birth name, height, mini biography

**Comment by uyar** [comment]
I have fixed some of the missing data. I will send them as a PR soon.

**Comment by uyar** [comment]
Also, the 'nick names' key should be changed to 'nicknames' without the space. Or a new key by that name should be added, IMHO.

**Comment by alberanid** [comment]
Correct: I've added the 'nicknames' alias (others were already present)

**Comment by uyar** [comment]
I've misplaced the expected and actual results in the issue description. Fixed now.
